npmPublishAccess: public

packageExtensions:
  "@babel/plugin-transform-react-display-name@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-pure-annotations@*":
    dependencies:
      "@babel/core": "*"
  "@equisoft/design-elements-react@*":
    dependencies:
      core-js: "*"
  "@radix-ui/react-select@*":
    dependencies:
      react-dom: ^17
  "@storybook/components@*":
    dependencies:
      react: ^17
      react-dom: ^17
  "@storybook/core-common@*":
    dependencies:
      "@storybook/react-webpack5": "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: ^17
  "@storybook/react@*":
    dependencies:
      react: ^17
  "@storybook/theming@*":
    dependencies:
      react: ^17
  react-shadow@*:
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses-audit.cjs
    spec: "https://raw.githubusercontent.com/tophat/yarn-plugin-licenses/master/bundles/@yarnpkg/plugin-licenses-audit.js"

yarnPath: .yarn/releases/yarn-4.3.1.cjs
