npmPublishAccess: public

packageExtensions:
  "@equisoft/design-elements-react@*":
    dependencies:
      core-js: "*"
  "@storybook/addon-docs@*":
    peerDependencies:
      "@babel/core": "*"
      webpack: "*"
  "@storybook/core-server@*":
    dependencies:
      "@storybook/manager-webpack5": "*"
  "@storybook/docs-tools@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/mdx1-csf@*":
    peerDependencies:
      "@babel/core": "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/client-api": "*"
      require-from-string: "*"
    peerDependencies:
      typescript: "*"
  "@storybook/telemetry@*":
    peerDependencies:
      react: "*"
      react-dom: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
      typescript: "*"
    peerDependencies:
      eslint: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
  react-shadow@*:
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-licenses-audit.cjs
    spec: "https://raw.githubusercontent.com/tophat/yarn-plugin-licenses/master/bundles/@yarnpkg/plugin-licenses-audit.js"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
