npmPublishAccess: public

packageExtensions:
  "@equisoft/design-elements-react@*":
    dependencies:
      core-js: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/react@*":
    dependencies:
      "@storybook/client-api": "*"
    peerDependencies:
      typescript: "*"
  "@storybook/theming@*":
    dependencies:
      "@emotion/serialize": "*"
      "@emotion/utils": "*"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
      typescript: "*"
    peerDependencies:
      eslint: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
  react-dev-utils@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: "*"
  react-shadow@*:
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"
  - path: .yarn/plugins/@yarnpkg/plugin-interactive-tools.cjs
    spec: "@yarnpkg/plugin-interactive-tools"

yarnPath: .yarn/releases/yarn-3.1.1.cjs
