packageExtensions:
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: '*'
  react-shadow@*:
    peerDependencies:
      styled-components: '*'
  '@equisoft/design-elements-react@*': # https://github.com/storybookjs/storybook/issues/11255
    dependencies:
      core-js: '3'

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"

yarnPath: .yarn/releases/yarn-2.3.3.cjs
