defaultSemverRangePrefix: ""

nodeLinker: node-modules

npmPublishAccess: public

packageExtensions:
  "@babel/plugin-transform-react-display-name@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-jsx@*":
    dependencies:
      "@babel/core": "*"
  "@babel/plugin-transform-react-pure-annotations@*":
    dependencies:
      "@babel/core": "*"
  "@cfaester/enzyme-adapter-react-18@*":
    dependencies:
      prop-types: "*"
  "@equisoft/design-elements-react@*":
    dependencies:
      core-js: "*"
  "@storybook/components@*":
    dependencies:
      react: ^18
      react-dom: ^18
  "@storybook/core@*":
    dependencies:
      "@storybook/react-webpack5": "*"
      react-docgen: "*"
  "@storybook/react-dom-shim@*":
    dependencies:
      react-dom: ^18
  "@storybook/react@*":
    dependencies:
      react: ^18
  "@storybook/theming@*":
    dependencies:
      react: ^18
  react-shadow@*:
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-licenses-audit.cjs
    spec: "https://raw.githubusercontent.com/tophat/yarn-plugin-licenses/master/bundles/@yarnpkg/plugin-licenses-audit.js"

yarnPath: .yarn/releases/yarn-4.12.0.cjs
