npmPublishAccess: public

packageExtensions:
  "@equisoft/design-elements-react@*":
    dependencies:
      core-js: "*"
  "@mdx-js/loader@*":
    peerDependencies:
      react: "*"
  "@storybook/react@*":
    peerDependencies:
      typescript: "*"
  eslint-module-utils@*:
    dependencies:
      "@typescript-eslint/parser": "*"
      typescript: "*"
  fork-ts-checker-webpack-plugin@*:
    dependencies:
      typescript: "*"
  react-dev-utils@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-loader@*:
    peerDependencies:
      webpack: "*"
  react-docgen-typescript-plugin@*:
    peerDependencies:
      webpack: "*"
  react-shadow@*:
    peerDependencies:
      styled-components: "*"

plugins:
  - path: .yarn/plugins/@yarnpkg/plugin-workspace-tools.cjs
    spec: "@yarnpkg/plugin-workspace-tools"
  - path: .yarn/plugins/@yarnpkg/plugin-version.cjs
    spec: "@yarnpkg/plugin-version"

yarnPath: .yarn/releases/yarn-2.4.0.cjs
