import type { ComponentTokenMap } from '../tokens';

export type ButtonToken =
    | 'button-primary-background-color'
    | 'button-primary-border-color'
    | 'button-primary-text-color'
    | 'button-primary-hover-background-color'
    | 'button-primary-hover-border-color'
    | 'button-primary-hover-text-color'
    | 'button-primary-disabled-background-color'
    | 'button-primary-disabled-border-color'
    | 'button-primary-disabled-text-color'
    | 'button-primary-inverted-background-color'
    | 'button-primary-inverted-border-color'
    | 'button-primary-inverted-text-color'
    | 'button-primary-inverted-hover-background-color'
    | 'button-primary-inverted-hover-border-color'
    | 'button-primary-inverted-hover-text-color'
    | 'button-primary-inverted-disabled-background-color'
    | 'button-primary-inverted-disabled-border-color'
    | 'button-primary-inverted-disabled-text-color'
    | 'button-secondary-background-color'
    | 'button-secondary-border-color'
    | 'button-secondary-text-color'
    | 'button-secondary-hover-background-color'
    | 'button-secondary-hover-border-color'
    | 'button-secondary-hover-text-color'
    | 'button-secondary-disabled-background-color'
    | 'button-secondary-disabled-border-color'
    | 'button-secondary-disabled-text-color'
    | 'button-secondary-inverted-background-color'
    | 'button-secondary-inverted-border-color'
    | 'button-secondary-inverted-text-color'
    | 'button-secondary-inverted-hover-background-color'
    | 'button-secondary-inverted-hover-border-color'
    | 'button-secondary-inverted-hover-text-color'
    | 'button-secondary-inverted-disabled-background-color'
    | 'button-secondary-inverted-disabled-border-color'
    | 'button-secondary-inverted-disabled-text-color'
    | 'button-tertiary-background-color'
    | 'button-tertiary-border-color'
    | 'button-tertiary-text-color'
    | 'button-tertiary-hover-background-color'
    | 'button-tertiary-hover-border-color'
    | 'button-tertiary-hover-text-color'
    | 'button-tertiary-disabled-background-color'
    | 'button-tertiary-disabled-border-color'
    | 'button-tertiary-disabled-text-color'
    | 'button-tertiary-inverted-background-color'
    | 'button-tertiary-inverted-border-color'
    | 'button-tertiary-inverted-text-color'
    | 'button-tertiary-inverted-hover-background-color'
    | 'button-tertiary-inverted-hover-border-color'
    | 'button-tertiary-inverted-hover-text-color'
    | 'button-tertiary-inverted-disabled-background-color'
    | 'button-tertiary-inverted-disabled-border-color'
    | 'button-tertiary-inverted-disabled-text-color'
    | 'button-destructive-primary-background-color'
    | 'button-destructive-primary-border-color'
    | 'button-destructive-primary-text-color'
    | 'button-destructive-primary-hover-background-color'
    | 'button-destructive-primary-hover-border-color'
    | 'button-destructive-primary-hover-text-color'
    | 'button-destructive-primary-disabled-background-color'
    | 'button-destructive-primary-disabled-border-color'
    | 'button-destructive-primary-disabled-text-color'
    | 'button-destructive-primary-inverted-background-color'
    | 'button-destructive-primary-inverted-border-color'
    | 'button-destructive-primary-inverted-text-color'
    | 'button-destructive-primary-inverted-hover-background-color'
    | 'button-destructive-primary-inverted-hover-border-color'
    | 'button-destructive-primary-inverted-hover-text-color'
    | 'button-destructive-primary-inverted-disabled-background-color'
    | 'button-destructive-primary-inverted-disabled-border-color'
    | 'button-destructive-primary-inverted-disabled-text-color'
    | 'button-destructive-secondary-background-color'
    | 'button-destructive-secondary-border-color'
    | 'button-destructive-secondary-text-color'
    | 'button-destructive-secondary-hover-background-color'
    | 'button-destructive-secondary-hover-border-color'
    | 'button-destructive-secondary-hover-text-color'
    | 'button-destructive-secondary-disabled-background-color'
    | 'button-destructive-secondary-disabled-border-color'
    | 'button-destructive-secondary-disabled-text-color'
    | 'button-destructive-secondary-inverted-background-color'
    | 'button-destructive-secondary-inverted-border-color'
    | 'button-destructive-secondary-inverted-text-color'
    | 'button-destructive-secondary-inverted-hover-background-color'
    | 'button-destructive-secondary-inverted-hover-border-color'
    | 'button-destructive-secondary-inverted-hover-text-color'
    | 'button-destructive-secondary-inverted-disabled-background-color'
    | 'button-destructive-secondary-inverted-disabled-border-color'
    | 'button-destructive-secondary-inverted-disabled-text-color'
    | 'button-destructive-tertiary-background-color'
    | 'button-destructive-tertiary-border-color'
    | 'button-destructive-tertiary-text-color'
    | 'button-destructive-tertiary-hover-background-color'
    | 'button-destructive-tertiary-hover-border-color'
    | 'button-destructive-tertiary-hover-text-color'
    | 'button-destructive-tertiary-disabled-background-color'
    | 'button-destructive-tertiary-disabled-border-color'
    | 'button-destructive-tertiary-disabled-text-color'
    | 'button-destructive-tertiary-inverted-background-color'
    | 'button-destructive-tertiary-inverted-border-color'
    | 'button-destructive-tertiary-inverted-text-color'
    | 'button-destructive-tertiary-inverted-hover-background-color'
    | 'button-destructive-tertiary-inverted-hover-border-color'
    | 'button-destructive-tertiary-inverted-hover-text-color'
    | 'button-destructive-tertiary-inverted-disabled-background-color'
    | 'button-destructive-tertiary-inverted-disabled-border-color'
    | 'button-destructive-tertiary-inverted-disabled-text-color'
    | 'button-input-background-color'
    | 'button-input-border-color'
    | 'button-input-text-color'
    | 'button-input-hover-background-color'
    | 'button-input-hover-border-color'
    | 'button-input-hover-text-color'
    | 'button-input-disabled-background-color'
    | 'button-input-disabled-border-color'
    | 'button-input-disabled-text-color';

export const defaultButtonTokens: ComponentTokenMap<ButtonToken> = {
    'button-primary-background-color': 'color-action',
    'button-primary-border-color': 'color-action',
    'button-primary-text-color': 'color-action-inverse',
    'button-primary-hover-background-color': 'color-action-hover',
    'button-primary-hover-border-color': 'color-action-hover',
    'button-primary-hover-text-color': 'color-action-inverse',
    'button-primary-disabled-background-color': 'color-action-disabled',
    'button-primary-disabled-border-color': 'color-action-disabled',
    'button-primary-disabled-text-color': 'color-action-inverse',
    'button-primary-inverted-background-color': 'color-action-inverse',
    'button-primary-inverted-border-color': 'color-action-inverse',
    'button-primary-inverted-text-color': 'color-action',
    'button-primary-inverted-hover-background-color': 'color-action-inverse-hover',
    'button-primary-inverted-hover-border-color': 'color-action-inverse-hover',
    'button-primary-inverted-hover-text-color': 'color-action-hover',
    'button-primary-inverted-disabled-background-color': 'color-action-inverse-disabled',
    'button-primary-inverted-disabled-border-color': 'color-action-inverse-disabled',
    'button-primary-inverted-disabled-text-color': 'color-action-disabled',
    'button-secondary-background-color': 'transparent-100',
    'button-secondary-border-color': 'color-action',
    'button-secondary-text-color': 'color-action',
    'button-secondary-hover-background-color': 'transparent-100',
    'button-secondary-hover-border-color': 'color-action-hover',
    'button-secondary-hover-text-color': 'color-action-hover',
    'button-secondary-disabled-background-color': 'transparent-100',
    'button-secondary-disabled-border-color': 'color-action-disabled',
    'button-secondary-disabled-text-color': 'color-action-disabled',
    'button-secondary-inverted-background-color': 'transparent-100',
    'button-secondary-inverted-border-color': 'color-action-inverse',
    'button-secondary-inverted-text-color': 'color-action-inverse',
    'button-secondary-inverted-hover-background-color': 'transparent-100',
    'button-secondary-inverted-hover-border-color': 'color-action-inverse-hover',
    'button-secondary-inverted-hover-text-color': 'color-action-inverse-hover',
    'button-secondary-inverted-disabled-background-color': 'transparent-100',
    'button-secondary-inverted-disabled-border-color': 'color-action-inverse-disabled',
    'button-secondary-inverted-disabled-text-color': 'color-action-inverse-disabled',
    'button-tertiary-background-color': 'transparent-100',
    'button-tertiary-border-color': 'transparent-100',
    'button-tertiary-text-color': 'color-content-subtle',
    'button-tertiary-hover-background-color': 'transparent-dark-15',
    'button-tertiary-hover-border-color': 'transparent-100',
    'button-tertiary-hover-text-color': 'color-content-hover',
    'button-tertiary-disabled-background-color': 'transparent-100',
    'button-tertiary-disabled-border-color': 'transparent-100',
    'button-tertiary-disabled-text-color': 'color-content-disabled',
    'button-tertiary-inverted-background-color': 'transparent-100',
    'button-tertiary-inverted-border-color': 'transparent-100',
    'button-tertiary-inverted-text-color': 'color-action-inverse',
    'button-tertiary-inverted-hover-background-color': 'transparent-dark-50',
    'button-tertiary-inverted-hover-border-color': 'transparent-100',
    'button-tertiary-inverted-hover-text-color': 'color-action-inverse',
    'button-tertiary-inverted-disabled-background-color': 'transparent-100',
    'button-tertiary-inverted-disabled-border-color': 'transparent-100',
    'button-tertiary-inverted-disabled-text-color': 'color-action-inverse-disabled',
    'button-destructive-primary-background-color': 'color-action-destructive',
    'button-destructive-primary-border-color': 'color-action-destructive',
    'button-destructive-primary-text-color': 'color-action-inverse',
    'button-destructive-primary-hover-background-color': 'color-action-destructive-hover',
    'button-destructive-primary-hover-border-color': 'color-action-destructive-hover',
    'button-destructive-primary-hover-text-color': 'color-action-inverse',
    'button-destructive-primary-disabled-background-color': 'color-action-destructive-disabled',
    'button-destructive-primary-disabled-border-color': 'color-action-destructive-disabled',
    'button-destructive-primary-disabled-text-color': 'color-action-inverse',
    'button-destructive-primary-inverted-background-color': 'color-action-inverse',
    'button-destructive-primary-inverted-border-color': 'color-action-inverse',
    'button-destructive-primary-inverted-text-color': 'color-action-destructive',
    'button-destructive-primary-inverted-hover-background-color': 'color-action-inverse',
    'button-destructive-primary-inverted-hover-border-color': 'color-action-inverse',
    'button-destructive-primary-inverted-hover-text-color': 'color-action-destructive-hover',
    'button-destructive-primary-inverted-disabled-background-color': 'color-action-inverse',
    'button-destructive-primary-inverted-disabled-border-color': 'color-action-inverse',
    'button-destructive-primary-inverted-disabled-text-color': 'color-action-destructive-disabled',
    'button-destructive-secondary-background-color': 'transparent-100',
    'button-destructive-secondary-border-color': 'color-action-destructive',
    'button-destructive-secondary-text-color': 'color-action-destructive',
    'button-destructive-secondary-hover-background-color': 'transparent-100',
    'button-destructive-secondary-hover-border-color': 'color-action-destructive-hover',
    'button-destructive-secondary-hover-text-color': 'color-action-destructive-hover',
    'button-destructive-secondary-disabled-background-color': 'transparent-100',
    'button-destructive-secondary-disabled-border-color': 'color-action-destructive-disabled',
    'button-destructive-secondary-disabled-text-color': 'color-action-destructive-disabled',
    'button-destructive-secondary-inverted-background-color': 'transparent-100',
    'button-destructive-secondary-inverted-border-color': 'color-action-destructive',
    'button-destructive-secondary-inverted-text-color': 'color-action-destructive',
    'button-destructive-secondary-inverted-hover-background-color': 'transparent-100',
    'button-destructive-secondary-inverted-hover-border-color': 'color-action-destructive-hover',
    'button-destructive-secondary-inverted-hover-text-color': 'color-action-destructive-hover',
    'button-destructive-secondary-inverted-disabled-background-color': 'transparent-100',
    'button-destructive-secondary-inverted-disabled-border-color': 'color-action-destructive-disabled',
    'button-destructive-secondary-inverted-disabled-text-color': 'color-action-destructive-disabled',
    'button-destructive-tertiary-background-color': 'transparent-100',
    'button-destructive-tertiary-border-color': 'transparent-100',
    'button-destructive-tertiary-text-color': 'color-action-destructive',
    'button-destructive-tertiary-hover-background-color': 'color-alert-05',
    'button-destructive-tertiary-hover-border-color': 'transparent-100',
    'button-destructive-tertiary-hover-text-color': 'color-action-destructive-hover',
    'button-destructive-tertiary-disabled-background-color': 'transparent-100',
    'button-destructive-tertiary-disabled-border-color': 'transparent-100',
    'button-destructive-tertiary-disabled-text-color': 'color-action-destructive-disabled',
    'button-destructive-tertiary-inverted-background-color': 'transparent-100',
    'button-destructive-tertiary-inverted-border-color': 'transparent-100',
    'button-destructive-tertiary-inverted-text-color': 'color-action-destructive',
    'button-destructive-tertiary-inverted-hover-background-color': 'color-alert-05',
    'button-destructive-tertiary-inverted-hover-border-color': 'transparent-100',
    'button-destructive-tertiary-inverted-hover-text-color': 'color-action-destructive-hover',
    'button-destructive-tertiary-inverted-disabled-background-color': 'transparent-100',
    'button-destructive-tertiary-inverted-disabled-border-color': 'transparent-100',
    'button-destructive-tertiary-inverted-disabled-text-color': 'color-action-destructive-disabled',
    'button-input-background-color': 'color-control-background',
    'button-input-border-color': 'color-control-border',
    'button-input-text-color': 'color-control-auxiliary',
    'button-input-hover-background-color': 'color-control-background-hover',
    'button-input-hover-border-color': 'color-control-border-hover',
    'button-input-hover-text-color': 'color-control-auxiliary-hover',
    'button-input-disabled-background-color': 'color-control-background-disabled',
    'button-input-disabled-border-color': 'color-control-border-disabled',
    'button-input-disabled-text-color': 'color-control-auxiliary-disabled',
};
