import type { ComponentTokenMap } from '../tokens';

export type TagToken =
    | 'tag-background-color'
    | 'tag-border-color'
    | 'tag-text-color'
    | 'tag-icon-color'
    | 'tag-hover-background-color'
    | 'tag-hover-border-color'
    | 'tag-hover-text-color'
    | 'tag-hover-icon-color'
    | 'tag-selected-background-color'
    | 'tag-selected-border-color'
    | 'tag-selected-text-color'
    | 'tag-selected-icon-color'
    | 'tag-decorative-01-background-color'
    | 'tag-decorative-01-border-color'
    | 'tag-decorative-01-text-color'
    | 'tag-decorative-01-icon-color'
    | 'tag-decorative-02-background-color'
    | 'tag-decorative-02-border-color'
    | 'tag-decorative-02-text-color'
    | 'tag-decorative-02-icon-color'
    | 'tag-decorative-03-background-color'
    | 'tag-decorative-03-border-color'
    | 'tag-decorative-03-text-color'
    | 'tag-decorative-03-icon-color'
    | 'tag-decorative-04-background-color'
    | 'tag-decorative-04-border-color'
    | 'tag-decorative-04-text-color'
    | 'tag-decorative-04-icon-color'
    | 'tag-decorative-05-background-color'
    | 'tag-decorative-05-border-color'
    | 'tag-decorative-05-text-color'
    | 'tag-decorative-05-icon-color'
    | 'tag-decorative-06-background-color'
    | 'tag-decorative-06-border-color'
    | 'tag-decorative-06-text-color'
    | 'tag-decorative-06-icon-color'
    | 'tag-decorative-07-background-color'
    | 'tag-decorative-07-border-color'
    | 'tag-decorative-07-text-color'
    | 'tag-decorative-07-icon-color'
    | 'tag-decorative-08-background-color'
    | 'tag-decorative-08-border-color'
    | 'tag-decorative-08-text-color'
    | 'tag-decorative-08-icon-color'
    | 'tag-decorative-09-background-color'
    | 'tag-decorative-09-border-color'
    | 'tag-decorative-09-text-color'
    | 'tag-decorative-09-icon-color'
    | 'tag-decorative-10-background-color'
    | 'tag-decorative-10-border-color'
    | 'tag-decorative-10-text-color'
    | 'tag-decorative-10-icon-color';

export const defaultTagTokens: ComponentTokenMap<TagToken> = {
    'tag-background-color': 'color-background-neutral-subtle',
    'tag-border-color': 'color-border-bold',
    'tag-text-color': 'color-content',
    'tag-icon-color': 'color-content',
    'tag-hover-background-color': 'color-background-hover',
    'tag-hover-border-color': 'color-border-hover',
    'tag-hover-icon-color': 'color-content-hover',
    'tag-hover-text-color': 'color-content-hover',
    'tag-selected-background-color': 'color-background-selected',
    'tag-selected-border-color': 'color-border-selected',
    'tag-selected-text-color': 'color-content-selected',
    'tag-selected-icon-color': 'color-content-selected',
    'tag-decorative-01-background-color': 'color-decorative-01-05',
    'tag-decorative-01-border-color': 'color-decorative-01-50',
    'tag-decorative-01-text-color': 'color-decorative-01-70',
    'tag-decorative-01-icon-color': 'color-decorative-01-70',
    'tag-decorative-02-background-color': 'color-decorative-02-05',
    'tag-decorative-02-border-color': 'color-decorative-02-50',
    'tag-decorative-02-text-color': 'color-decorative-02-70',
    'tag-decorative-02-icon-color': 'color-decorative-02-70',
    'tag-decorative-03-background-color': 'color-decorative-03-05',
    'tag-decorative-03-border-color': 'color-decorative-03-50',
    'tag-decorative-03-text-color': 'color-decorative-03-70',
    'tag-decorative-03-icon-color': 'color-decorative-03-70',
    'tag-decorative-04-background-color': 'color-decorative-04-05',
    'tag-decorative-04-border-color': 'color-decorative-04-50',
    'tag-decorative-04-text-color': 'color-decorative-04-70',
    'tag-decorative-04-icon-color': 'color-decorative-04-70',
    'tag-decorative-05-background-color': 'color-decorative-05-05',
    'tag-decorative-05-border-color': 'color-decorative-05-50',
    'tag-decorative-05-text-color': 'color-decorative-05-70',
    'tag-decorative-05-icon-color': 'color-decorative-05-70',
    'tag-decorative-06-background-color': 'color-decorative-06-05',
    'tag-decorative-06-border-color': 'color-decorative-06-50',
    'tag-decorative-06-text-color': 'color-decorative-06-70',
    'tag-decorative-06-icon-color': 'color-decorative-06-70',
    'tag-decorative-07-background-color': 'color-decorative-07-05',
    'tag-decorative-07-border-color': 'color-decorative-07-50',
    'tag-decorative-07-text-color': 'color-decorative-07-70',
    'tag-decorative-07-icon-color': 'color-decorative-07-70',
    'tag-decorative-08-background-color': 'color-decorative-08-05',
    'tag-decorative-08-border-color': 'color-decorative-08-50',
    'tag-decorative-08-text-color': 'color-decorative-08-70',
    'tag-decorative-08-icon-color': 'color-decorative-08-70',
    'tag-decorative-09-background-color': 'color-decorative-09-05',
    'tag-decorative-09-border-color': 'color-decorative-09-50',
    'tag-decorative-09-text-color': 'color-decorative-09-70',
    'tag-decorative-09-icon-color': 'color-decorative-09-70',
    'tag-decorative-10-background-color': 'color-decorative-10-05',
    'tag-decorative-10-border-color': 'color-decorative-10-50',
    'tag-decorative-10-text-color': 'color-decorative-10-70',
    'tag-decorative-10-icon-color': 'color-decorative-10-70',
};
