export type PaletteTokens =
    | 'color-brand-05'
    | 'color-brand-20'
    | 'color-brand-50'
    | 'color-brand-70'
    | 'color-brand-80'
    | 'color-accent-20'
    | 'color-accent-50'
    | 'color-accent-70'
    | 'color-white'
    | 'color-black'
    | 'color-neutral-02'
    | 'color-neutral-05'
    | 'color-neutral-15'
    | 'color-neutral-30'
    | 'color-neutral-50'
    | 'color-neutral-65'
    | 'color-neutral-90'
    | 'color-alert-02'
    | 'color-alert-05'
    | 'color-alert-20'
    | 'color-alert-50'
    | 'color-alert-70'
    | 'color-informative-02'
    | 'color-informative-05'
    | 'color-informative-20'
    | 'color-informative-50'
    | 'color-informative-70'
    | 'color-success-02'
    | 'color-success-05'
    | 'color-success-20'
    | 'color-success-50'
    | 'color-success-70'
    | 'color-warning-02'
    | 'color-warning-05'
    | 'color-warning-20'
    | 'color-warning-50'
    | 'color-warning-70'
    | 'color-warning-80'
    | 'color-discovery-02'
    | 'color-discovery-05'
    | 'color-discovery-20'
    | 'color-discovery-50'
    | 'color-discovery-70';

export type PaletteValue = string;

export type PaletteTokenMap = {
    [Token in PaletteTokens]: PaletteValue;
};
