import { NoSelfReference } from '../../utility-types';
import { RefTokens } from './ref-tokens';

export type AliasTokens =
    // TIER 1
    // BACKGROUND
    | 'color-bg-surface'
    | 'color-bg-surface-alternate'
    | 'color-bg-surface-brand'
    | 'color-bg-surface-brand-hover'
    | 'color-bg-surface-brand-selected'
    | 'color-bg-fill'
    | 'color-bg-fill-disabled'
    | 'color-bg-fill-hover'
    | 'color-bg-fill-selected'
    | 'color-bg-fill-inverse'
    | 'color-bg-fill-inverse-hover'
    | 'color-bg-fill-alternate-disabled'
    | 'color-bg-fill-alternate-hover'
    | 'color-indicator-bg-fill'
    | 'color-action-bg-fill'
    | 'color-action-bg-fill-hover'
    | 'color-action-bg-fill-disabled'
    | 'color-feedback-bg-surface-success'
    | 'color-feedback-bg-surface-warning'
    | 'color-feedback-bg-surface-alert'
    | 'color-feedback-bg-surface-discovery'
    | 'color-feedback-bg-surface-informative'
    | 'color-feedback-bg-fill-success'
    | 'color-feedback-bg-fill-success-hover'
    | 'color-feedback-bg-fill-alert'
    | 'color-feedback-bg-fill-alert-hover'
    | 'color-feedback-bg-fill-warning'
    | 'color-feedback-bg-fill-warning-hover'
    | 'color-feedback-bg-fill-discovery'
    | 'color-feedback-bg-fill-discovery-hover'
    | 'color-feedback-bg-fill-informative'
    | 'color-feedback-bg-fill-informative-hover'
    // BORDER
    | 'color-border-lightest'
    | 'color-border-lighter'
    | 'color-border-light'
    | 'color-border-mid'
    | 'color-border-dark'
    | 'color-border-darker'
    | 'color-border-darkest'
    | 'color-action-border-light'
    | 'color-action-border-mid'
    | 'color-action-border-dark'
    | 'color-border'
    | 'color-form-border'
    | 'color-border-alternate'
    | 'color-border-selected'
    | 'color-border-alternate-selected'
    | 'color-border-inverse'
    | 'color-border-disabled'
    | 'color-border-hover'
    | 'color-border-error'
    | 'color-border-focus-outside'
    | 'color-border-focus-inside'
    | 'color-border-focus-outside-inverse'
    | 'color-border-focus-inside-inverse'
    | 'color-action-border'
    | 'color-action-border-hover'
    | 'color-action-border-disabled'
    | 'color-feedback-border-success'
    | 'color-feedback-border-warning'
    | 'color-feedback-border-alert'
    | 'color-feedback-border-discovery'
    | 'color-feedback-border-informative'
    // CONTENT
    | 'color-content'
    | 'color-content-alternate'
    | 'color-content-inverse'
    | 'color-content-disabled'
    | 'color-content-brand'
    | 'color-content-hover'
    | 'color-content-selected'
    | 'color-content-error'
    | 'color-link-content'
    | 'color-link-content-visited'
    | 'color-link-content-disabled'
    | 'color-link-content-hover'
    | 'color-action-content'
    | 'color-action-content-hover'
    | 'color-action-content-disabled'
    | 'color-feedback-content-success'
    | 'color-feedback-content-warning'
    | 'color-feedback-content-alert'
    | 'color-feedback-content-discovery'
    | 'color-feedback-content-informative'
    // TIER 2
    | 'separator-color'
    // TEXT
    | 'color-text'
    | 'color-text-alternate'
    | 'color-text-inverse'
    | 'color-text-disabled'
    | 'color-text-brand'
    | 'color-text-hover'
    | 'color-text-selected'
    | 'color-text-error'
    | 'color-link-text'
    | 'color-link-text-visited'
    | 'color-link-text-disabled'
    | 'color-link-text-hover'
    | 'color-action-text'
    | 'color-action-text-hover'
    | 'color-action-text-disabled'
    | 'color-feedback-text-success'
    | 'color-feedback-text-warning'
    | 'color-feedback-text-alert'
    | 'color-feedback-text-discovery'
    | 'color-feedback-text-informative'
    // ICON
    | 'color-icon'
    | 'color-icon-alternate'
    | 'color-icon-inverse'
    | 'color-icon-disabled'
    | 'color-icon-brand'
    | 'color-icon-hover'
    | 'color-icon-selected'
    | 'color-icon-error'
    | 'color-link-icon'
    | 'color-link-icon-visited'
    | 'color-link-icon-disabled'
    | 'color-link-icon-hover'
    | 'color-action-icon'
    | 'color-action-icon-hover'
    | 'color-action-icon-disabled'
    | 'color-feedback-icon-success'
    | 'color-feedback-icon-warning'
    | 'color-feedback-icon-alert'
    | 'color-feedback-icon-discovery'
    | 'color-feedback-icon-informative'

export type AliasTokenMap = {
    [Token in AliasTokens]: NoSelfReference<RefTokens | AliasTokens, Token>;
}

export const defaultAliasTokens: AliasTokenMap = {
    // TIER 1
    // BACKGROUND
    'color-bg-surface': 'color-white',
    'color-bg-surface-alternate': 'color-neutral-02',
    'color-bg-surface-brand': 'color-brand-80',
    'color-bg-surface-brand-hover': 'color-brand-70',
    'color-bg-surface-brand-selected': 'color-brand-70',
    'color-bg-fill': 'color-white',
    'color-bg-fill-disabled': 'color-neutral-05',
    'color-bg-fill-hover': 'color-neutral-15',
    'color-bg-fill-selected': 'color-brand-05',
    'color-bg-fill-inverse': 'color-neutral-65',
    'color-bg-fill-inverse-hover': 'color-neutral-90',
    'color-bg-fill-alternate-disabled': 'color-neutral-15',
    'color-bg-fill-alternate-hover': 'color-neutral-30',
    'color-indicator-bg-fill': 'color-brand-50',
    'color-action-bg-fill': 'color-brand-50',
    'color-action-bg-fill-hover': 'color-brand-70',
    'color-action-bg-fill-disabled': 'color-brand-20',
    'color-feedback-bg-surface-success': 'color-success-05',
    'color-feedback-bg-surface-warning': 'color-warning-05',
    'color-feedback-bg-surface-alert': 'color-alert-05',
    'color-feedback-bg-surface-discovery': 'color-discovery-05',
    'color-feedback-bg-surface-informative': 'color-informative-05',
    'color-feedback-bg-fill-success': 'color-success-50',
    'color-feedback-bg-fill-success-hover': 'color-success-70',
    'color-feedback-bg-fill-alert': 'color-alert-50',
    'color-feedback-bg-fill-alert-hover': 'color-alert-70',
    'color-feedback-bg-fill-warning': 'color-warning-50',
    'color-feedback-bg-fill-warning-hover': 'color-warning-70',
    'color-feedback-bg-fill-discovery': 'color-discovery-50',
    'color-feedback-bg-fill-discovery-hover': 'color-discovery-70',
    'color-feedback-bg-fill-informative': 'color-informative-50',
    'color-feedback-bg-fill-informative-hover': 'color-informative-70',
    // BORDER
    // TIER 1
    'color-border-lightest': 'color-white',
    'color-border-lighter': 'color-neutral-05',
    'color-border-light': 'color-neutral-15',
    'color-border-mid': 'color-neutral-30',
    'color-border-dark': 'color-neutral-50',
    'color-border-darker': 'color-neutral-65',
    'color-border-darkest': 'color-neutral-90',
    'color-action-border-light': 'color-brand-20',
    'color-action-border-mid': 'color-brand-50',
    'color-action-border-dark': 'color-brand-70',
    'color-border-error': 'color-alert-50',
    'color-feedback-border-success': 'color-success-50',
    'color-feedback-border-warning': 'color-warning-50',
    'color-feedback-border-alert': 'color-alert-50',
    'color-feedback-border-discovery': 'color-discovery-50',
    'color-feedback-border-informative': 'color-informative-50',
    'color-border-focus-outside': 'color-brand-50',
    'color-border-focus-inside': 'color-brand-20',

    // TIER 2
    'color-border': 'color-border-light',
    'color-border-inverse': 'color-border-lightest',
    'color-border-alternate': 'color-border-dark',
    'color-form-border': 'color-border-darker',
    'color-border-hover': 'color-border-darkest',
    'color-border-disabled': 'color-border-mid',
    'color-border-selected': 'color-action-border-mid',
    'color-border-alternate-selected': 'color-action-border-dark',
    'color-action-border': 'color-action-border-mid',
    'color-action-border-hover': 'color-action-border-dark',
    'color-action-border-disabled': 'color-action-border-light',
    'color-border-focus-outside-inverse': 'color-border-focus-inside',
    'color-border-focus-inside-inverse': 'color-border-focus-outside',

    // CONTENT
    'color-content': 'color-neutral-90',
    'color-content-alternate': 'color-neutral-65',
    'color-content-inverse': 'color-white',
    'color-content-disabled': 'color-neutral-30',
    'color-content-brand': 'color-brand-70',
    'color-content-hover': 'color-black',
    'color-content-selected': 'color-brand-70',
    'color-content-error': 'color-alert-50',
    'color-link-content': 'color-informative-50',
    'color-link-content-disabled': 'color-informative-20',
    'color-link-content-hover': 'color-informative-70',
    'color-link-content-visited': 'color-discovery-50',
    'color-action-content': 'color-brand-50',
    'color-action-content-hover': 'color-brand-70',
    'color-action-content-disabled': 'color-brand-20',
    'color-feedback-content-success': 'color-success-70',
    'color-feedback-content-warning': 'color-warning-80',
    'color-feedback-content-alert': 'color-alert-70',
    'color-feedback-content-discovery': 'color-discovery-70',
    'color-feedback-content-informative': 'color-informative-70',
    // TIER 2
    'separator-color': 'color-border',
    // TEXT
    'color-text': 'color-content',
    'color-text-alternate': 'color-content-alternate',
    'color-text-inverse': 'color-content-inverse',
    'color-text-disabled': 'color-content-disabled',
    'color-text-brand': 'color-content-brand',
    'color-text-hover': 'color-content-hover',
    'color-text-selected': 'color-content-selected',
    'color-text-error': 'color-content-error',
    'color-link-text': 'color-link-content',
    'color-link-text-visited': 'color-link-content-visited',
    'color-link-text-disabled': 'color-link-content-disabled',
    'color-link-text-hover': 'color-link-content-hover',
    'color-action-text': 'color-action-content',
    'color-action-text-hover': 'color-action-content-hover',
    'color-action-text-disabled': 'color-action-content-disabled',
    'color-feedback-text-success': 'color-feedback-content-success',
    'color-feedback-text-warning': 'color-feedback-content-warning',
    'color-feedback-text-alert': 'color-feedback-content-alert',
    'color-feedback-text-discovery': 'color-feedback-content-discovery',
    'color-feedback-text-informative': 'color-feedback-content-informative',
    // ICON
    'color-icon': 'color-content',
    'color-icon-alternate': 'color-content-alternate',
    'color-icon-inverse': 'color-content-inverse',
    'color-icon-disabled': 'color-content-disabled',
    'color-icon-brand': 'color-content-brand',
    'color-icon-hover': 'color-content-hover',
    'color-icon-selected': 'color-content-selected',
    'color-icon-error': 'color-content-error',
    'color-link-icon': 'color-link-content',
    'color-link-icon-visited': 'color-link-content-visited',
    'color-link-icon-disabled': 'color-link-content-disabled',
    'color-link-icon-hover': 'color-link-content-hover',
    'color-action-icon': 'color-action-content',
    'color-action-icon-hover': 'color-action-content-hover',
    'color-action-icon-disabled': 'color-action-content-disabled',
    'color-feedback-icon-success': 'color-feedback-content-success',
    'color-feedback-icon-warning': 'color-feedback-content-warning',
    'color-feedback-icon-alert': 'color-feedback-content-alert',
    'color-feedback-icon-discovery': 'color-feedback-content-discovery',
    'color-feedback-icon-informative': 'color-feedback-content-informative',
};
