import { type FC } from 'react';
import {
    AlertCircle,
    AlertOctagon,
    AlertTriangle,
    ArchiveRestore,
    Archive,
    ArrowDown,
    ArrowDownNarrowWide,
    ArrowLeft,
    ArrowRight,
    ArrowUp,
    ArrowUpNarrowWide,
    Baseline,
    Bell,
    Blocks,
    Bold,
    Brain,
    Briefcase,
    Building,
    Cake,
    Calendar,
    CalendarCheck,
    CalendarPlus2,
    CalendarSync,
    ChartNoAxesColumn,
    ChartPie,
    Check,
    CheckCircle,
    ChevronDown,
    ChevronLeft,
    ChevronRight,
    ChevronUp,
    ChevronsDown,
    ChevronsLeft,
    ChevronsRight,
    ChevronsUp,
    ChevronsUpDown,
    Cigarette,
    Circle,
    CircleArrowDown,
    CircleArrowUp,
    CircleDollarSign,
    CircleMinus,
    CirclePlus,
    CircleStop,
    CircleX,
    Clipboard,
    ClipboardCheck,
    ClipboardList,
    ClipboardPlus,
    Clock,
    CloudSync,
    Contact,
    CornerDownRight,
    Copy,
    Database,
    DollarSign,
    Download,
    ExternalLink,
    Eye,
    EyeOff,
    File,
    FileImage,
    FileText,
    Files,
    Flag,
    Folder,
    FolderOpen,
    Frown,
    Funnel,
    Globe,
    Grip,
    GripVertical,
    HandCoins,
    Heading1,
    Heading2,
    Heading3,
    Heading4,
    Heading5,
    Heading6,
    Heart,
    HeartPulse,
    HelpCircle,
    Highlighter,
    History,
    Home,
    Image,
    Info,
    Italic,
    Languages,
    Layers,
    Lightbulb,
    Link,
    List,
    ListOrdered,
    Loader,
    Lock,
    LogIn,
    LogOut,
    Mail,
    MailPlus,
    MapPin,
    Maximize2,
    Megaphone,
    Menu,
    MessageCircle,
    MessagesSquare,
    Minimize2,
    Minus,
    Moon,
    MoreHorizontal,
    MoreVertical,
    MoveDown,
    MoveUp,
    NotebookTabs,
    NotepadText,
    PanelLeft,
    PanelRight,
    PanelRightClose,
    PanelRightOpen,
    Paperclip,
    Pencil,
    PenLine,
    Phone,
    Plus,
    Printer,
    Receipt,
    Redo2,
    RefreshCw,
    RemoveFormatting,
    Repeat,
    RotateCcw,
    RotateCw,
    Save,
    Search,
    Send,
    Settings,
    Settings2,
    Share,
    Share2,
    Shield,
    ShieldAlert,
    ShieldCheck,
    ShieldOff,
    ShieldQuestionMark,
    ShieldUser,
    ShieldX,
    Shuffle,
    SlidersVertical,
    SquarePen,
    SquaresUnite,
    Star,
    Strikethrough,
    Table,
    Target,
    TextAlignCenter,
    TextAlignEnd,
    TextAlignJustify,
    TextAlignStart,
    TextQuote,
    ThumbsDown,
    ThumbsUp,
    Trash2,
    TrendingUp,
    Type,
    Umbrella,
    Underline,
    Undo2,
    Unlink,
    Unlock,
    Upload,
    UploadCloud,
    User,
    UserRoundPlus,
    Users,
    VenusAndMars,
    Video,
    Wallet,
    Wrench,
    X,
} from 'lucide-react';
import AlertFilled from '../../icons/alert-filled.svg';
import WarningFilled from '../../icons/warning-filled.svg';
import Equisoft from '../../logos/logo-equisoft-ico.svg';

const iconMapping = {
    alertCircle: AlertCircle,
    alertFilled: AlertFilled,
    alertOctagon: AlertOctagon,
    alertShield: ShieldAlert,
    alertTriangle: AlertTriangle,
    archive: Archive,
    arrowAscending: ArrowDownNarrowWide,
    arrowDescending: ArrowUpNarrowWide,
    arrowDown: ArrowDown,
    arrowDownCircle: CircleArrowDown,
    arrowLeft: ArrowLeft,
    arrowRight: ArrowRight,
    arrowUp: ArrowUp,
    arrowUpCircle: CircleArrowUp,
    baseline: Baseline,
    bell: Bell,
    bento: Grip,
    blocks: Blocks,
    bold: Bold,
    brain: Brain,
    briefcase: Briefcase,
    cake: Cake,
    calendar: Calendar,
    calendarAdd: CalendarPlus2,
    calendarCheck: CalendarCheck,
    calendarSync: CalendarSync,
    check: Check,
    checkCircle: CheckCircle,
    chevronDown: ChevronDown,
    chevronLeft: ChevronLeft,
    chevronRight: ChevronRight,
    chevronUp: ChevronUp,
    chevronsDown: ChevronsDown,
    chevronsLeft: ChevronsLeft,
    chevronsRight: ChevronsRight,
    chevronsUp: ChevronsUp,
    cigarette: Cigarette,
    circle: Circle,
    clipboard: Clipboard,
    clipboardCheck: ClipboardCheck,
    clipboardList: ClipboardList,
    clipboardPlus: ClipboardPlus,
    clock: Clock,
    cloudSync: CloudSync,
    contact: Contact,
    copy: Copy,
    cornerDownRight: CornerDownRight,
    database: Database,
    dollarSign: DollarSign,
    dollarSignCircle: CircleDollarSign,
    download: Download,
    drag: GripVertical,
    edit: Pencil,
    editShape: SquarePen,
    equisoft: Equisoft,
    externalLink: ExternalLink,
    export: Share,
    eye: Eye,
    eyeOff: EyeOff,
    file: File,
    fileImage: FileImage,
    files: Files,
    fileText: FileText,
    flag: Flag,
    folder: Folder,
    frown: Frown,
    funnel: Funnel,
    gender: VenusAndMars,
    globe: Globe,
    graph: ChartNoAxesColumn,
    handCoins: HandCoins,
    heading1: Heading1,
    heading2: Heading2,
    heading3: Heading3,
    heading4: Heading4,
    heading5: Heading5,
    heading6: Heading6,
    heart: Heart,
    heartPulse: HeartPulse,
    helpCircle: HelpCircle,
    highlighter: Highlighter,
    history: History,
    home: Home,
    image: Image,
    info: Info,
    italic: Italic,
    languages: Languages,
    layers: Layers,
    lightbulb: Lightbulb,
    link: Link,
    list: List,
    listOrdered: ListOrdered,
    loader: Loader,
    lock: Lock,
    logIn: LogIn,
    logOut: LogOut,
    mail: Mail,
    mailPlus: MailPlus,
    mapPin: MapPin,
    maximize: Maximize2,
    megaphone: Megaphone,
    menu: Menu,
    merge: SquaresUnite,
    messageCircle: MessageCircle,
    messagesSquare: MessagesSquare,
    minimize: Minimize2,
    minus: Minus,
    minusCircle: CircleMinus,
    moon: Moon,
    moreHorizontal: MoreHorizontal,
    moreVertical: MoreVertical,
    notepadText: NotepadText,
    notebookTabs: NotebookTabs,
    open: FolderOpen,
    organization: Building,
    panelLeft: PanelRightOpen,
    panelRight: PanelRightClose,
    panelRightClose: PanelRightClose,
    panelRightOpen: PanelRightOpen,
    paperclip: Paperclip,
    penLine: PenLine,
    phone: Phone,
    pieChart: ChartPie,
    plus: Plus,
    plusCircle: CirclePlus,
    plusSign: Plus,
    printer: Printer,
    receipt: Receipt,
    redo: Redo2,
    removeFormatting: RemoveFormatting,
    reorder: ChevronsUpDown,
    reorderDown: MoveDown,
    reorderUp: MoveUp,
    repeat: Repeat,
    restore: ArchiveRestore,
    rotateCcw: RotateCcw,
    rotateCw: RotateCw,
    save: Save,
    search: Search,
    send: Send,
    settings: Settings,
    settingsSliders: Settings2,
    share: Share2,
    shield: Shield,
    shieldCheck: ShieldCheck,
    shieldOff: ShieldOff,
    shieldQuestionMark: ShieldQuestionMark,
    shieldUser: ShieldUser,
    shieldX: ShieldX,
    shuffle: Shuffle,
    sidebarLeft: PanelLeft,
    sidebarRight: PanelRight,
    star: Star,
    stopCircle: CircleStop,
    strikethrough: Strikethrough,
    table: Table,
    target: Target,
    textAlignCenter: TextAlignCenter,
    textAlignEnd: TextAlignEnd,
    textAlignJustify: TextAlignJustify,
    textAlignStart: TextAlignStart,
    textQuote: TextQuote,
    thumbsDown: ThumbsDown,
    thumbsUp: ThumbsUp,
    transfer: RefreshCw,
    trash: Trash2,
    trendingUp: TrendingUp,
    type: Type,
    umbrella: Umbrella,
    undo: Undo2,
    underline: Underline,
    unlink: Unlink,
    unlock: Unlock,
    upload: Upload,
    uploadCloud: UploadCloud,
    user: User,
    userRoundPlus: UserRoundPlus,
    users: Users,
    verticalSliders: SlidersVertical,
    video: Video,
    wallet: Wallet,
    warningFilled: WarningFilled,
    wrench: Wrench,
    x: X,
    xCircle: CircleX,
} as const;

export type IconName = keyof typeof iconMapping;

export interface IconProps {
    className?: string;
    /** Name of the icon, has to be in IconName */
    name: IconName;
    focusable?: boolean;
    /**
     * Size will affect both width and height
     * @default 24
     */
    size?: string;
    /**
     * Icon's color, in any format supported by css (keyword, rgb, hex, etc.)
     * @default currentColor
     */
    color?: string;
    role?: string;
}

export const Icon: FC<IconProps> = ({
    className,
    name,
    size = '24',
    color = 'currentColor',
    role,
    ...props
}: IconProps) => {
    const Component = iconMapping[name];

    if (!Component) {
        return null;
    }

    return (
        <Component
            className={className}
            height={size}
            focusable={false}
            width={size}
            color={color}
            role={role}
            {...props /* eslint-disable-line react/jsx-props-no-spreading */}
        />
    );
};

Icon.displayName = 'Icon';
