import type { AliasTokenMap } from '../tokens';

export type ColorAliasToken =
    | 'color-action'
    | 'color-action-hover'
    | 'color-action-disabled'
    | 'color-action-destructive'
    | 'color-action-destructive-hover'
    | 'color-action-destructive-disabled'
    | 'color-action-inverse'
    | 'color-action-inverse-hover'
    | 'color-action-inverse-disabled'
    | 'color-background-neutral-subtlest'
    | 'color-background-neutral-subtle'
    | 'color-background-neutral-bold'
    | 'color-background-neutral-bold-disabled'
    | 'color-feedback-background-success-subtle'
    | 'color-feedback-background-warning-subtle'
    | 'color-feedback-background-alert-subtle'
    | 'color-feedback-background-discovery-subtle'
    | 'color-feedback-background-informative-subtle'
    | 'color-feedback-background-success-subtlest'
    | 'color-feedback-background-warning-subtlest'
    | 'color-feedback-background-alert-subtlest'
    | 'color-feedback-background-discovery-subtlest'
    | 'color-feedback-background-informative-subtlest'
    | 'color-feedback-background-success-bold'
    | 'color-feedback-background-success-bold-disabled'
    | 'color-feedback-background-alert-bold'
    | 'color-feedback-background-warning-bold'
    | 'color-feedback-background-discovery-bold'
    | 'color-feedback-background-informative-bold'
    | 'color-feedback-border-success'
    | 'color-feedback-border-warning'
    | 'color-feedback-border-alert'
    | 'color-feedback-border-discovery'
    | 'color-feedback-border-informative'
    | 'color-feedback-content-success'
    | 'color-feedback-content-warning'
    | 'color-feedback-content-alert'
    | 'color-feedback-content-discovery'
    | 'color-feedback-content-informative'
    | 'color-control-background'
    | 'color-control-background-hover'
    | 'color-control-background-disabled'
    | 'color-control-background-readonly'
    | 'color-control-background-checked'
    | 'color-control-background-selected'
    | 'color-control-background-selected-hover'
    | 'color-control-border'
    | 'color-control-border-hover'
    | 'color-control-border-disabled'
    | 'color-control-border-readonly'
    | 'color-control-border-selected'
    | 'color-control-border-checked'
    | 'color-control-border-error'
    | 'color-control-value'
    | 'color-control-value-hover'
    | 'color-control-value-disabled'
    | 'color-control-value-readonly'
    | 'color-control-auxiliary'
    | 'color-control-auxiliary-hover'
    | 'color-control-auxiliary-disabled'
    | 'color-control-auxiliary-readonly'
    | 'color-control-auxiliary-error'
    | 'color-control-auxiliary-success'
    | 'color-control-auxiliary-checked'
    | 'color-control-auxiliary-selected'
    | 'color-menu-background'
    | 'color-menu-border'
    | 'color-menu-item-background'
    | 'color-menu-item-background-hover'
    | 'color-menu-item-content'
    | 'color-menu-item-subcontent'
    | 'color-menu-item-content-hover'
    | 'color-menu-item-content-disabled'
    | 'color-background-brand-subtle'
    | 'color-background-brand'
    | 'color-background-brand-bold'
    | 'color-background-indicator-disabled'
    | 'color-background-indicator-selected'
    | 'color-background-indicator-active'
    | 'color-border-brand'
    | 'color-border-brand-bold'
    | 'color-content-brand'
    | 'color-background'
    | 'color-background-overlay'
    | 'color-background-isolated'
    | 'color-background-disabled'
    | 'color-background-empty'
    | 'color-background-hover'
    | 'color-background-selected'
    | 'color-background-selected-hover'
    | 'color-backdrop-background'
    | 'color-backdrop-background-subtle'
    | 'color-border'
    | 'color-border-subtle'
    | 'color-border-bold'
    | 'color-border-overlay'
    | 'color-border-hover'
    | 'color-border-disabled'
    | 'color-border-empty'
    | 'color-border-selected'
    | 'color-border-inverse'
    | 'color-border-focus-outside'
    | 'color-border-focus-inside'
    | 'color-border-focus-outside-inverse'
    | 'color-border-focus-inside-inverse'
    | 'color-content'
    | 'color-content-subtle'
    | 'color-content-inverse'
    | 'color-content-disabled'
    | 'color-content-hover'
    | 'color-content-selected'
    | 'color-link-content'
    | 'color-link-content-visited'
    | 'color-link-content-disabled'
    | 'color-link-content-hover'
    | 'color-box-shadow';

export const defaultColorAliasTokens: AliasTokenMap<ColorAliasToken> = {
    'color-action': 'color-brand-50',
    'color-action-hover': 'color-brand-70',
    'color-action-disabled': 'color-brand-20',
    'color-action-destructive': 'color-alert-50',
    'color-action-destructive-hover': 'color-alert-70',
    'color-action-destructive-disabled': 'color-alert-20',
    'color-action-inverse': 'color-white',
    'color-action-inverse-hover': 'color-brand-20',
    'color-action-inverse-disabled': 'color-brand-50',
    'color-background-neutral-subtlest': 'color-neutral-02',
    'color-background-neutral-subtle': 'color-neutral-05',
    'color-background-neutral-bold': 'color-neutral-65',
    'color-background-neutral-bold-disabled': 'color-neutral-30',
    'color-feedback-background-success-subtlest': 'color-success-02',
    'color-feedback-background-success-subtle': 'color-success-05',
    'color-feedback-background-success-bold': 'color-success-50',
    'color-feedback-background-success-bold-disabled': 'color-success-20',
    'color-feedback-border-success': 'color-success-50',
    'color-feedback-content-success': 'color-success-70',
    'color-feedback-background-alert-subtlest': 'color-alert-02',
    'color-feedback-background-alert-subtle': 'color-alert-05',
    'color-feedback-background-alert-bold': 'color-alert-50',
    'color-feedback-border-alert': 'color-alert-50',
    'color-feedback-content-alert': 'color-alert-70',
    'color-feedback-background-warning-subtlest': 'color-warning-02',
    'color-feedback-background-warning-subtle': 'color-warning-05',
    'color-feedback-background-warning-bold': 'color-warning-50',
    'color-feedback-border-warning': 'color-warning-50',
    'color-feedback-content-warning': 'color-warning-80',
    'color-feedback-background-discovery-subtlest': 'color-discovery-02',
    'color-feedback-background-discovery-subtle': 'color-discovery-05',
    'color-feedback-background-discovery-bold': 'color-discovery-50',
    'color-feedback-border-discovery': 'color-discovery-50',
    'color-feedback-content-discovery': 'color-discovery-70',
    'color-feedback-background-informative-subtlest': 'color-informative-02',
    'color-feedback-background-informative-subtle': 'color-informative-05',
    'color-feedback-background-informative-bold': 'color-informative-50',
    'color-feedback-border-informative': 'color-informative-50',
    'color-feedback-content-informative': 'color-informative-70',
    'color-control-background': 'color-white',
    'color-control-background-hover': 'color-neutral-15',
    'color-control-background-disabled': 'color-neutral-05',
    'color-control-background-readonly': 'transparent-dark-3',
    'color-control-background-checked': 'color-brand-50',
    'color-control-background-selected': 'color-brand-05',
    'color-control-background-selected-hover': 'color-brand-10',
    'color-control-border': 'color-neutral-65',
    'color-control-border-hover': 'color-black',
    'color-control-border-disabled': 'color-neutral-30',
    'color-control-border-readonly': 'transparent-100',
    'color-control-border-selected': 'color-brand-50',
    'color-control-border-checked': 'color-brand-50',
    'color-control-border-error': 'color-alert-50',
    'color-control-value': 'color-content',
    'color-control-value-hover': 'color-content-hover',
    'color-control-value-disabled': 'color-content-disabled',
    'color-control-value-readonly': 'color-content',
    'color-control-auxiliary': 'color-neutral-65',
    'color-control-auxiliary-hover': 'color-black',
    'color-control-auxiliary-disabled': 'color-neutral-30',
    'color-control-auxiliary-readonly': 'color-neutral-65',
    'color-control-auxiliary-error': 'color-alert-50',
    'color-control-auxiliary-success': 'color-success-50',
    'color-control-auxiliary-checked': 'color-white',
    'color-control-auxiliary-selected': 'color-brand-70',
    'color-menu-background': 'color-background-overlay',
    'color-menu-border': 'color-border-overlay',
    'color-menu-item-background': 'transparent-100',
    'color-menu-item-background-hover': 'color-background-hover', // should use transparency instead
    'color-menu-item-content': 'color-content',
    'color-menu-item-subcontent': 'color-content-subtle',
    'color-menu-item-content-hover': 'color-content-hover',
    'color-menu-item-content-disabled': 'color-content-disabled',
    'color-background-brand-subtle': 'color-brand-20',
    'color-background-brand': 'color-brand-50',
    'color-background-brand-bold': 'color-brand-80',
    'color-background-indicator-disabled': 'color-neutral-30',
    'color-background-indicator-selected': 'color-brand-50',
    'color-background-indicator-active': 'color-brand-80',
    'color-border-brand': 'color-brand-50',
    'color-border-brand-bold': 'color-brand-70',
    'color-content-brand': 'color-brand-50',
    'color-background': 'color-white',
    'color-background-overlay': 'color-white',
    'color-background-isolated': 'color-neutral-02',
    'color-background-hover': 'color-neutral-15',
    'color-background-disabled': 'color-neutral-05',
    'color-background-empty': 'color-neutral-15',
    'color-background-selected': 'color-brand-05',
    'color-background-selected-hover': 'color-brand-10', // should use transparency instead
    'color-backdrop-background': 'transparent-dark-75',
    'color-backdrop-background-subtle': 'transparent-dark-50',
    'color-border': 'color-neutral-15',
    'color-border-subtle': 'color-neutral-05',
    'color-border-bold': 'color-neutral-50',
    'color-border-overlay': 'color-neutral-50',
    'color-border-inverse': 'color-white',
    'color-border-hover': 'color-black',
    'color-border-disabled': 'color-neutral-15',
    'color-border-empty': 'color-neutral-30',
    'color-border-selected': 'color-brand-50',
    'color-border-focus-outside': 'color-brand-50',
    'color-border-focus-inside': 'color-brand-20',
    'color-border-focus-outside-inverse': 'color-border-focus-inside',
    'color-border-focus-inside-inverse': 'color-border-focus-outside',
    'color-content': 'color-neutral-90',
    'color-content-subtle': 'color-neutral-65',
    'color-content-inverse': 'color-white',
    'color-content-hover': 'color-black',
    'color-content-disabled': 'color-neutral-30',
    'color-content-selected': 'color-brand-70',
    'color-link-content': 'color-informative-50',
    'color-link-content-disabled': 'color-informative-20',
    'color-link-content-hover': 'color-informative-70',
    'color-link-content-visited': 'color-informative-50',
    'color-box-shadow': 'transparent-dark-20',
};
