import type { AliasTokenMap } from '../tokens';

export type TextAliasToken =
    | 'text-heading-xl-font-family'
    | 'text-heading-xl-font-weight'
    | 'text-heading-xl-font-size'
    | 'text-heading-xl-line-height'
    | 'text-heading-xl-letter-spacing'
    | 'text-heading-xl-transform'
    | 'text-heading-lg-font-family'
    | 'text-heading-lg-font-weight'
    | 'text-heading-lg-font-size'
    | 'text-heading-lg-line-height'
    | 'text-heading-lg-letter-spacing'
    | 'text-heading-lg-transform'
    | 'text-heading-md-font-family'
    | 'text-heading-md-font-weight'
    | 'text-heading-md-font-size'
    | 'text-heading-md-line-height'
    | 'text-heading-md-letter-spacing'
    | 'text-heading-md-transform'
    | 'text-heading-sm-font-family'
    | 'text-heading-sm-font-weight'
    | 'text-heading-sm-font-size'
    | 'text-heading-sm-line-height'
    | 'text-heading-sm-letter-spacing'
    | 'text-heading-sm-transform'
    | 'text-heading-xs-font-family'
    | 'text-heading-xs-font-weight'
    | 'text-heading-xs-font-size'
    | 'text-heading-xs-line-height'
    | 'text-heading-xs-letter-spacing'
    | 'text-heading-xs-transform'
    | 'text-body-lg-font-family'
    | 'text-body-lg-font-weight'
    | 'text-body-lg-font-size'
    | 'text-body-lg-line-height'
    | 'text-body-lg-letter-spacing'
    | 'text-body-lg-transform'
    | 'text-body-md-font-family'
    | 'text-body-md-font-weight'
    | 'text-body-md-font-size'
    | 'text-body-md-line-height'
    | 'text-body-md-letter-spacing'
    | 'text-body-md-transform'
    | 'text-body-sm-font-family'
    | 'text-body-sm-font-weight'
    | 'text-body-sm-font-size'
    | 'text-body-sm-line-height'
    | 'text-body-sm-letter-spacing'
    | 'text-body-sm-transform'
    | 'text-highlight-lg-font-family'
    | 'text-highlight-lg-font-weight'
    | 'text-highlight-lg-font-size'
    | 'text-highlight-lg-line-height'
    | 'text-highlight-lg-letter-spacing'
    | 'text-highlight-lg-transform'
    | 'text-highlight-md-font-family'
    | 'text-highlight-md-font-weight'
    | 'text-highlight-md-font-size'
    | 'text-highlight-md-line-height'
    | 'text-highlight-md-letter-spacing'
    | 'text-highlight-md-transform'
    | 'text-highlight-sm-font-family'
    | 'text-highlight-sm-font-weight'
    | 'text-highlight-sm-font-size'
    | 'text-highlight-sm-line-height'
    | 'text-highlight-sm-letter-spacing'
    | 'text-highlight-sm-transform'
    | 'text-action-md-font-family'
    | 'text-action-md-font-weight'
    | 'text-action-md-font-size'
    | 'text-action-md-line-height'
    | 'text-action-md-letter-spacing'
    | 'text-action-md-transform'
    | 'text-action-sm-font-family'
    | 'text-action-sm-font-weight'
    | 'text-action-sm-font-size'
    | 'text-action-sm-line-height'
    | 'text-action-sm-letter-spacing'
    | 'text-action-sm-transform'
    | 'text-label-md-font-family'
    | 'text-label-md-font-weight'
    | 'text-label-md-font-size'
    | 'text-label-md-line-height'
    | 'text-label-md-letter-spacing'
    | 'text-label-md-transform'
    | 'text-label-sm-font-family'
    | 'text-label-sm-font-weight'
    | 'text-label-sm-font-size'
    | 'text-label-sm-line-height'
    | 'text-label-sm-letter-spacing'
    | 'text-label-sm-transform'
    | 'text-legend-sm-font-family'
    | 'text-legend-sm-font-weight'
    | 'text-legend-sm-font-size'
    | 'text-legend-sm-line-height'
    | 'text-legend-sm-letter-spacing'
    | 'text-legend-sm-transform'
    | 'text-caption-md-font-family'
    | 'text-caption-md-font-weight'
    | 'text-caption-md-font-size'
    | 'text-caption-md-line-height'
    | 'text-caption-md-letter-spacing'
    | 'text-caption-md-transform';

export const defaultTextAliasTokens: AliasTokenMap<TextAliasToken> = {
    'text-heading-xl-font-family': 'font-family-brand',
    'text-heading-xl-font-weight': 'font-weight-semibold',
    'text-heading-xl-font-size': 'font-size-800',
    'text-heading-xl-line-height': 'line-height-1000',
    'text-heading-xl-letter-spacing': 'letter-spacing-normal',
    'text-heading-xl-transform': 'font-transform-none',
    'text-heading-lg-font-family': 'font-family-brand',
    'text-heading-lg-font-weight': 'font-weight-semibold',
    'text-heading-lg-font-size': 'font-size-600',
    'text-heading-lg-line-height': 'line-height-800',
    'text-heading-lg-letter-spacing': 'letter-spacing-normal',
    'text-heading-lg-transform': 'font-transform-none',
    'text-heading-md-font-family': 'font-family-brand',
    'text-heading-md-font-weight': 'font-weight-semibold',
    'text-heading-md-font-size': 'font-size-500',
    'text-heading-md-line-height': 'line-height-700',
    'text-heading-md-letter-spacing': 'letter-spacing-normal',
    'text-heading-md-transform': 'font-transform-none',
    'text-heading-sm-font-family': 'font-family-brand',
    'text-heading-sm-font-weight': 'font-weight-semibold',
    'text-heading-sm-font-size': 'font-size-400',
    'text-heading-sm-line-height': 'line-height-600',
    'text-heading-sm-letter-spacing': 'letter-spacing-normal',
    'text-heading-sm-transform': 'font-transform-none',
    'text-heading-xs-font-family': 'font-family-brand',
    'text-heading-xs-font-weight': 'font-weight-semibold',
    'text-heading-xs-font-size': 'font-size-350',
    'text-heading-xs-line-height': 'line-height-500',
    'text-heading-xs-letter-spacing': 'letter-spacing-normal',
    'text-heading-xs-transform': 'font-transform-none',
    'text-body-lg-font-family': 'font-family-sans',
    'text-body-lg-font-weight': 'font-weight-regular',
    'text-body-lg-font-size': 'font-size-400',
    'text-body-lg-line-height': 'line-height-600',
    'text-body-lg-letter-spacing': 'letter-spacing-normal',
    'text-body-lg-transform': 'font-transform-none',
    'text-body-md-font-family': 'font-family-sans',
    'text-body-md-font-weight': 'font-weight-regular',
    'text-body-md-font-size': 'font-size-350',
    'text-body-md-line-height': 'line-height-600',
    'text-body-md-letter-spacing': 'letter-spacing-normal',
    'text-body-md-transform': 'font-transform-none',
    'text-body-sm-font-family': 'font-family-sans',
    'text-body-sm-font-weight': 'font-weight-regular',
    'text-body-sm-font-size': 'font-size-300',
    'text-body-sm-line-height': 'line-height-500',
    'text-body-sm-letter-spacing': 'letter-spacing-normal',
    'text-body-sm-transform': 'font-transform-none',
    'text-highlight-lg-font-family': 'font-family-sans',
    'text-highlight-lg-font-weight': 'text-heading-lg-font-weight',
    'text-highlight-lg-font-size': 'text-heading-lg-font-size',
    'text-highlight-lg-line-height': 'text-heading-lg-line-height',
    'text-highlight-lg-letter-spacing': 'text-heading-lg-letter-spacing',
    'text-highlight-lg-transform': 'text-heading-lg-transform',
    'text-highlight-md-font-family': 'font-family-sans',
    'text-highlight-md-font-weight': 'text-heading-md-font-weight',
    'text-highlight-md-font-size': 'text-heading-md-font-size',
    'text-highlight-md-line-height': 'text-heading-md-line-height',
    'text-highlight-md-letter-spacing': 'text-heading-md-letter-spacing',
    'text-highlight-md-transform': 'text-heading-md-transform',
    'text-highlight-sm-font-family': 'font-family-sans',
    'text-highlight-sm-font-weight': 'text-heading-sm-font-weight',
    'text-highlight-sm-font-size': 'text-heading-sm-font-size',
    'text-highlight-sm-line-height': 'text-heading-sm-line-height',
    'text-highlight-sm-letter-spacing': 'text-heading-sm-letter-spacing',
    'text-highlight-sm-transform': 'text-heading-sm-transform',
    'text-action-md-font-family': 'text-body-sm-font-family',
    'text-action-md-font-weight': 'font-weight-bold',
    'text-action-md-font-size': 'text-body-sm-font-size',
    'text-action-md-line-height': 'line-height-600',
    'text-action-md-letter-spacing': 'text-body-sm-letter-spacing',
    'text-action-md-transform': 'font-transform-uppercase',
    'text-action-sm-font-family': 'text-body-sm-font-family',
    'text-action-sm-font-weight': 'font-weight-bold',
    'text-action-sm-font-size': 'font-size-275',
    'text-action-sm-line-height': 'line-height-600',
    'text-action-sm-letter-spacing': 'text-body-sm-letter-spacing',
    'text-action-sm-transform': 'font-transform-uppercase',
    'text-label-md-font-family': 'text-body-md-font-family',
    'text-label-md-font-weight': 'text-body-md-font-weight',
    'text-label-md-font-size': 'text-body-md-font-size',
    'text-label-md-line-height': 'text-body-md-line-height',
    'text-label-md-letter-spacing': 'text-body-md-letter-spacing',
    'text-label-md-transform': 'text-body-md-transform',
    'text-label-sm-font-family': 'text-body-sm-font-family',
    'text-label-sm-font-weight': 'text-body-sm-font-weight',
    'text-label-sm-font-size': 'text-body-sm-font-size',
    'text-label-sm-line-height': 'text-body-sm-line-height',
    'text-label-sm-letter-spacing': 'text-body-sm-letter-spacing',
    'text-label-sm-transform': 'text-body-sm-transform',
    'text-legend-sm-font-family': 'text-body-sm-font-family',
    'text-legend-sm-font-weight': 'text-body-sm-font-weight',
    'text-legend-sm-font-size': 'text-body-sm-font-size',
    'text-legend-sm-line-height': 'text-body-sm-line-height',
    'text-legend-sm-letter-spacing': 'text-body-sm-letter-spacing',
    'text-legend-sm-transform': 'text-body-sm-transform',
    'text-caption-md-font-family': 'text-body-md-font-family',
    'text-caption-md-font-weight': 'text-body-md-font-weight',
    'text-caption-md-font-size': 'text-body-md-font-size',
    'text-caption-md-line-height': 'text-body-md-line-height',
    'text-caption-md-letter-spacing': 'text-body-md-letter-spacing',
    'text-caption-md-transform': 'text-body-md-transform',
};
