import type { AliasTokenMap } from '../tokens';

export type TextAliasToken =
    | 'text-heading-font-family'
    | 'text-heading-font-weight'
    | 'text-heading-letter-spacing'
    | 'text-heading-transform'
    | 'text-heading-xsmall-font-size'
    | 'text-heading-xsmall-line-height'
    | 'text-heading-small-font-size'
    | 'text-heading-small-line-height'
    | 'text-heading-medium-font-size'
    | 'text-heading-medium-line-height'
    | 'text-heading-large-font-size'
    | 'text-heading-large-line-height'
    | 'text-heading-xlarge-font-size'
    | 'text-heading-xlarge-line-height'
    | 'text-body-font-family'
    | 'text-body-font-weight'
    | 'text-body-letter-spacing'
    | 'text-body-transform'
    | 'text-body-strong-font-weight'
    | 'text-body-small-font-size'
    | 'text-body-small-line-height'
    | 'text-body-medium-font-size'
    | 'text-body-medium-line-height'
    | 'text-body-large-font-size'
    | 'text-body-large-line-height'
    | 'text-emphasis-font-family'
    | 'text-emphasis-font-weight'
    | 'text-emphasis-letter-spacing'
    | 'text-emphasis-transform'
    | 'text-emphasis-small-font-size'
    | 'text-emphasis-small-line-height'
    | 'text-emphasis-medium-font-size'
    | 'text-emphasis-medium-line-height'
    | 'text-emphasis-large-font-size'
    | 'text-emphasis-large-line-height'
    | 'text-caps-font-family'
    | 'text-caps-font-weight'
    | 'text-caps-letter-spacing'
    | 'text-caps-transform'
    | 'text-caps-small-font-size'
    | 'text-caps-small-line-height'
    | 'text-caps-medium-font-size'
    | 'text-caps-medium-line-height'
    | 'text-label-font-family'
    | 'text-label-font-weight'
    | 'text-label-letter-spacing'
    | 'text-label-transform'
    | 'text-label-small-font-size'
    | 'text-label-small-line-height'
    | 'text-label-medium-font-size'
    | 'text-label-medium-line-height'
    | 'text-label-medium-letter-spacing'
    | 'text-label-medium-transform'
    | 'text-label-small-font-family'
    | 'text-label-small-font-weight'
    | 'text-label-small-font-size'
    | 'text-label-small-line-height'
    | 'text-label-small-letter-spacing'
    | 'text-label-small-transform'
    | 'text-legend-large-font-family'
    | 'text-legend-large-font-weight'
    | 'text-legend-large-font-size'
    | 'text-legend-large-line-height'
    | 'text-legend-large-letter-spacing'
    | 'text-legend-large-transform'
    | 'text-legend-medium-font-family'
    | 'text-legend-medium-font-weight'
    | 'text-legend-medium-font-size'
    | 'text-legend-medium-line-height'
    | 'text-legend-medium-letter-spacing'
    | 'text-legend-medium-transform'
    | 'text-legend-small-font-family'
    | 'text-legend-small-font-weight'
    | 'text-legend-small-font-size'
    | 'text-legend-small-line-height'
    | 'text-legend-small-letter-spacing'
    | 'text-legend-small-transform'
    | 'text-legend-xsmall-font-family'
    | 'text-legend-xsmall-font-weight'
    | 'text-legend-xsmall-font-size'
    | 'text-legend-xsmall-line-height'
    | 'text-legend-xsmall-letter-spacing'
    | 'text-legend-xsmall-transform'
    | 'text-legend-xxsmall-font-family'
    | 'text-legend-xxsmall-font-weight'
    | 'text-legend-xxsmall-font-size'
    | 'text-legend-xxsmall-line-height'
    | 'text-legend-xxsmall-letter-spacing'
    | 'text-legend-xxsmall-transform'
    | 'text-caption-medium-font-family'
    | 'text-caption-medium-font-weight'
    | 'text-caption-medium-font-size'
    | 'text-caption-medium-line-height'
    | 'text-caption-large-font-size'
    | 'text-caption-large-line-height';

export const defaultTextAliasTokens: AliasTokenMap<TextAliasToken> = {
    'text-heading-font-family': 'font-family-brand',
    'text-heading-font-weight': 'font-weight-semibold',
    'text-heading-letter-spacing': 'letter-spacing-normal',
    'text-heading-transform': 'font-transform-none',
    'text-heading-xsmall-font-size': 'font-size-350',
    'text-heading-xsmall-line-height': 'line-height-500',
    'text-heading-small-font-size': 'font-size-400',
    'text-heading-small-line-height': 'line-height-600',
    'text-heading-medium-font-size': 'font-size-500',
    'text-heading-medium-line-height': 'line-height-700',
    'text-heading-large-font-size': 'font-size-600',
    'text-heading-large-line-height': 'line-height-800',
    'text-heading-xlarge-font-size': 'font-size-800',
    'text-heading-xlarge-line-height': 'line-height-1000',
    'text-body-font-family': 'font-family-sans',
    'text-body-font-weight': 'font-weight-regular',
    'text-body-letter-spacing': 'letter-spacing-normal',
    'text-body-transform': 'font-transform-none',
    'text-body-strong-font-weight': 'font-weight-semibold',
    'text-body-small-font-size': 'font-size-300',
    'text-body-small-line-height': 'line-height-400',
    'text-body-medium-font-size': 'font-size-350',
    'text-body-medium-line-height': 'line-height-500',
    'text-body-large-font-size': 'font-size-400',
    'text-body-large-line-height': 'line-height-600',
    'text-emphasis-font-family': 'text-heading-font-family',
    'text-emphasis-font-weight': 'text-heading-font-weight',
    'text-emphasis-letter-spacing': 'text-heading-letter-spacing',
    'text-emphasis-transform': 'text-heading-transform',
    'text-emphasis-small-font-size': 'text-heading-small-font-size',
    'text-emphasis-small-line-height': 'text-heading-small-line-height',
    'text-emphasis-medium-font-size': 'text-heading-medium-font-size',
    'text-emphasis-medium-line-height': 'text-heading-medium-line-height',
    'text-emphasis-large-font-size': 'text-heading-large-font-size',
    'text-emphasis-large-line-height': 'text-heading-large-line-height',
    'text-caps-font-family': 'font-family-sans',
    'text-caps-font-weight': 'font-weight-bold',
    'text-caps-letter-spacing': 'letter-spacing-normal',
    'text-caps-transform': 'font-transform-uppercase',
    'text-caps-small-font-size': 'font-size-275',
    'text-caps-small-line-height': 'line-height-600',
    'text-caps-medium-font-size': 'font-size-300',
    'text-caps-medium-line-height': 'line-height-600',
    'text-label-font-family': 'text-body-font-family',
    'text-label-font-weight': 'text-body-font-weight',
    'text-label-letter-spacing': 'text-body-letter-spacing',
    'text-label-transform': 'text-body-transform',
    'text-label-small-font-size': 'text-body-small-font-size',
    'text-label-small-line-height': 'line-height-500',
    'text-label-medium-font-size': 'text-body-medium-font-size',
    'text-label-medium-line-height': 'text-body-medium-line-height',
    'text-label-medium-letter-spacing': 'text-body-medium-letter-spacing',
    'text-label-medium-transform': 'text-body-medium-transform',
    'text-label-small-font-family': 'text-body-small-font-family',
    'text-label-small-font-weight': 'text-body-small-font-weight',
    'text-label-small-font-size': 'text-body-small-font-size',
    'text-label-small-line-height': 'text-body-small-line-height',
    'text-label-small-letter-spacing': 'text-body-small-letter-spacing',
    'text-label-small-transform': 'text-body-small-transform',
    'text-legend-large-font-family': 'text-heading-large-font-family',
    'text-legend-large-font-weight': 'text-heading-large-font-weight',
    'text-legend-large-font-size': 'text-heading-large-font-size',
    'text-legend-large-line-height': 'text-heading-large-line-height',
    'text-legend-large-letter-spacing': 'text-heading-large-letter-spacing',
    'text-legend-large-transform': 'text-heading-large-transform',
    'text-legend-medium-font-family': 'text-body-small-font-family',
    'text-legend-medium-font-weight': 'text-body-small-font-weight',
    'text-legend-medium-font-size': 'text-heading-medium-font-size',
    'text-legend-medium-line-height': 'text-heading-medium-line-height',
    'text-legend-medium-letter-spacing': 'text-heading-medium-letter-spacing',
    'text-legend-medium-transform': 'text-heading-medium-transform',
    'text-legend-small-font-family': 'text-heading-small-font-family',
    'text-legend-small-font-weight': 'text-heading-small-font-weight',
    'text-legend-small-font-size': 'text-heading-small-font-size',
    'text-legend-small-line-height': 'text-heading-small-line-height',
    'text-legend-small-letter-spacing': 'text-heading-small-letter-spacing',
    'text-legend-small-transform': 'text-heading-small-transform',
    'text-legend-xsmall-font-family': 'text-heading-xsmall-font-family',
    'text-legend-xsmall-font-weight': 'text-heading-xsmall-font-weight',
    'text-legend-xsmall-font-size': 'text-heading-xsmall-font-size',
    'text-legend-xsmall-line-height': 'text-heading-xsmall-line-height',
    'text-legend-xsmall-letter-spacing': 'text-heading-xsmall-letter-spacing',
    'text-legend-xsmall-transform': 'text-heading-xsmall-transform',
    'text-legend-xxsmall-font-family': 'text-body-small-font-family',
    'text-legend-xxsmall-font-weight': 'text-body-small-font-weight',
    'text-legend-xxsmall-font-size': 'font-size-300',
    'text-legend-xxsmall-line-height': 'line-height-400',
    'text-legend-xxsmall-letter-spacing': 'letter-spacing-normal',
    'text-legend-xxsmall-transform': 'font-transform-none',
    'text-caption-medium-font-family': 'text-body-medium-font-family',
    'text-caption-medium-font-weight': 'text-body-medium-font-weight',
    'text-caption-medium-font-size': 'text-body-medium-font-size',
    'text-caption-medium-line-height': 'text-body-medium-line-height',
    'text-caption-medium-letter-spacing': 'text-body-medium-letter-spacing',
    'text-caption-medium-transform': 'text-body-medium-transform',
};
