import { ComponentTokens } from './component-tokens';
import { Palette } from './palette';

export function generateTokens(palette: Palette): ComponentTokens {
    return {
        'button-primary-background-color': palette['color-brand-50'],
        'button-primary-inverted-background-color': palette['color-white'],
        'button-primary-border-color': palette['color-brand-50'],
        'button-primary-inverted-border-color': palette['color-white'],
        'button-primary-text-color': palette['color-white'],
        'button-primary-inverted-text-color': palette['color-brand-50'],

        'button-primary-hover-background-color': palette['color-brand-70'],
        'button-primary-inverted-hover-background-color': palette['color-white'],
        'button-primary-hover-border-color': palette['color-brand-70'],
        'button-primary-inverted-hover-border-color': palette['color-white'],
        'button-primary-hover-text-color': palette['color-white'],
        'button-primary-inverted-hover-text-color': palette['color-brand-70'],

        'button-primary-focus-background-color': palette['color-brand-50'],
        'button-primary-inverted-focus-background-color': palette['color-white'],
        'button-primary-focus-border-color': palette['color-brand-50'],
        'button-primary-inverted-focus-border-color': palette['color-white'],
        'button-primary-focus-text-color': palette['color-white'],
        'button-primary-inverted-focus-text-color': palette['color-brand-50'],

        'button-primary-disabled-background-color': palette['color-brand-20'],
        'button-primary-inverted-disabled-background-color': palette['color-white'],
        'button-primary-disabled-border-color': palette['color-brand-20'],
        'button-primary-inverted-disabled-border-color': palette['color-white'],
        'button-primary-disabled-text-color': palette['color-white'],
        'button-primary-inverted-disabled-text-color': palette['color-brand-20'],

        'button-secondary-background-color': palette['color-white'],
        'button-secondary-inverted-background-color': 'transparent',
        'button-secondary-border-color': palette['color-brand-50'],
        'button-secondary-inverted-border-color': palette['color-white'],
        'button-secondary-text-color': palette['color-brand-50'],
        'button-secondary-inverted-text-color': palette['color-white'],

        'button-secondary-hover-background-color': palette['color-white'],
        'button-secondary-inverted-hover-background-color': 'transparent',
        'button-secondary-hover-border-color': palette['color-brand-70'],
        'button-secondary-inverted-hover-border-color': palette['color-brand-20'],
        'button-secondary-hover-text-color': palette['color-brand-70'],
        'button-secondary-inverted-hover-text-color': palette['color-brand-20'],

        'button-secondary-focus-background-color': palette['color-white'],
        'button-secondary-inverted-focus-background-color': palette['color-brand-80'],
        'button-secondary-focus-border-color': palette['color-brand-50'],
        'button-secondary-inverted-focus-border-color': palette['color-brand-50'],
        'button-secondary-focus-text-color': palette['color-brand-50'],
        'button-secondary-inverted-focus-text-color': palette['color-white'],

        'button-secondary-disabled-background-color': palette['color-white'],
        'button-secondary-inverted-disabled-background-color': 'transparent',
        'button-secondary-disabled-border-color': palette['color-brand-20'],
        'button-secondary-inverted-disabled-border-color': palette['color-brand-50'],
        'button-secondary-disabled-text-color': palette['color-brand-20'],
        'button-secondary-inverted-disabled-text-color': palette['color-brand-50'],

        'button-tertiary-background-color': 'transparent',
        'button-tertiary-inverted-background-color': 'transparent',
        'button-tertiary-border-color': 'transparent',
        'button-tertiary-inverted-border-color': 'transparent',
        'button-tertiary-text-color': palette['color-neutral-65'],
        'button-tertiary-inverted-text-color': palette['color-white'],

        'button-tertiary-hover-background-color': palette['color-neutral-15'],
        'button-tertiary-inverted-hover-background-color': palette['color-brand-70'],
        'button-tertiary-hover-border-color': 'transparent',
        'button-tertiary-inverted-hover-border-color': 'transparent',
        'button-tertiary-hover-text-color': palette['color-black'],
        'button-tertiary-inverted-hover-text-color': palette['color-white'],

        'button-tertiary-focus-background-color': palette['color-white'],
        'button-tertiary-inverted-focus-background-color': palette['color-brand-80'],
        'button-tertiary-focus-border-color': palette['color-brand-50'],
        'button-tertiary-inverted-focus-border-color': palette['color-brand-50'],
        'button-tertiary-focus-text-color': palette['color-neutral-65'],
        'button-tertiary-inverted-focus-text-color': palette['color-white'],

        'button-tertiary-disabled-background-color': 'transparent',
        'button-tertiary-inverted-disabled-background-color': 'transparent',
        'button-tertiary-disabled-border-color': 'transparent',
        'button-tertiary-inverted-disabled-border-color': 'transparent',
        'button-tertiary-disabled-text-color': palette['color-neutral-30'],
        'button-tertiary-inverted-disabled-text-color': palette['color-brand-50'],

        'button-destructive-background-color': palette['color-alert-50'],
        'button-destructive-inverted-background-color': palette['color-white'],
        'button-destructive-border-color': palette['color-alert-50'],
        'button-destructive-inverted-border-color': palette['color-white'],
        'button-destructive-text-color': palette['color-white'],
        'button-destructive-inverted-text-color': palette['color-alert-50'],

        'button-destructive-hover-background-color': palette['color-alert-70'],
        'button-destructive-inverted-hover-background-color': palette['color-white'],
        'button-destructive-hover-border-color': palette['color-alert-70'],
        'button-destructive-inverted-hover-border-color': palette['color-white'],
        'button-destructive-hover-text-color': palette['color-white'],
        'button-destructive-inverted-hover-text-color': palette['color-alert-70'],

        'button-destructive-focus-background-color': palette['color-alert-50'],
        'button-destructive-inverted-focus-background-color': palette['color-white'],
        'button-destructive-focus-border-color': palette['color-alert-20'],
        'button-destructive-inverted-focus-border-color': palette['color-white'],
        'button-destructive-focus-text-color': palette['color-white'],
        'button-destructive-inverted-focus-text-color': palette['color-alert-20'],

        'button-destructive-disabled-background-color': palette['color-alert-20'],
        'button-destructive-inverted-disabled-background-color': palette['color-white'],
        'button-destructive-disabled-border-color': palette['color-alert-20'],
        'button-destructive-inverted-disabled-border-color': palette['color-white'],
        'button-destructive-disabled-text-color': palette['color-white'],
        'button-destructive-inverted-disabled-text-color': palette['color-alert-20'],
        // TODO: fix destructive secondary colors
        'button-destructive-secondary-background-color': palette['color-alert-50'],
        'button-destructive-secondary-inverted-background-color': palette['color-white'],
        'button-destructive-secondary-border-color': palette['color-alert-50'],
        'button-destructive-secondary-inverted-border-color': palette['color-white'],
        'button-destructive-secondary-text-color': palette['color-white'],
        'button-destructive-secondary-inverted-text-color': palette['color-alert-50'],

        'button-destructive-secondary-hover-background-color': palette['color-alert-70'],
        'button-destructive-secondary-inverted-hover-background-color': palette['color-white'],
        'button-destructive-secondary-hover-border-color': palette['color-alert-70'],
        'button-destructive-secondary-inverted-hover-border-color': palette['color-white'],
        'button-destructive-secondary-hover-text-color': palette['color-white'],
        'button-destructive-secondary-inverted-hover-text-color': palette['color-alert-70'],

        'button-destructive-secondary-focus-background-color': palette['color-alert-50'],
        'button-destructive-secondary-inverted-focus-background-color': palette['color-white'],
        'button-destructive-secondary-focus-border-color': palette['color-alert-20'],
        'button-destructive-secondary-inverted-focus-border-color': palette['color-white'],
        'button-destructive-secondary-focus-text-color': palette['color-white'],
        'button-destructive-secondary-inverted-focus-text-color': palette['color-alert-20'],

        'button-destructive-secondary-disabled-background-color': palette['color-alert-20'],
        'button-destructive-secondary-inverted-disabled-background-color': palette['color-white'],
        'button-destructive-secondary-disabled-border-color': palette['color-alert-20'],
        'button-destructive-secondary-inverted-disabled-border-color': palette['color-white'],
        'button-destructive-secondary-disabled-text-color': palette['color-white'],
        'button-destructive-secondary-inverted-disabled-text-color': palette['color-alert-20'],

        'button-search-background-color': palette['color-white'],
        'button-search-border-color': palette['color-neutral-65'],
        'button-search-text-color': palette['color-neutral-65'],
        'button-search-hover-background-color': palette['color-neutral-15'],
        'button-search-hover-text-color': palette['color-black'],
        'button-search-disabled-background-color': palette['color-neutral-05'],
        'button-search-disabled-border-color': palette['color-neutral-15'],
        'button-search-disabled-text-color': palette['color-neutral-30'],
    };
}
