import { Theme } from './default-types';

export const generateTokens = (ref: Theme['ref']): Theme['tokens'] => {
    const tokens: Theme['tokens'] = {
        'focus-box-shadow': `0 0 0 2px ${ref['color-brand-20']}`,
        'focus-box-shadow-inset': `inset 0 0 0 2px ${ref['color-brand-20']}`,
        'focus-border-box-shadow': ` 0 0 0 1px ${ref['color-brand-50']}, 0 0 0 3px ${ref['color-brand-20']}`,
        'focus-border-box-shadow-inset': `inset 0 0 0 2px ${ref['color-brand-20']}, inset 0 0 0 3px ${ref['color-brand-50']}`,
        'focus-border': `${ref['color-brand-50']}`,
        'modal-overlay-background-color': 'rgba(0, 0, 0, 0.75)',
        'overlay-box-shadow': '0 10px 20px 0 rgba(0, 0, 0, 0.19)',

        'button-primary-bg': `${ref['color-brand-50']}`,
        'button-primary-inverted-bg': `${ref['color-white']}`,
        'button-primary-border': `${ref['color-brand-50']}`,
        'button-primary-inverted-border': `${ref['color-white']}`,
        'button-primary-color': `${ref['color-white']}`,
        'button-primary-inverted-color': `${ref['color-brand-50']}`,

        'button-primary-hover-bg': `${ref['color-brand-70']}`,
        'button-primary-inverted-hover-bg': `${ref['color-white']}`,
        'button-primary-hover-border': `${ref['color-brand-70']}`,
        'button-primary-inverted-hover-border': `${ref['color-white']}`,
        'button-primary-hover-color': `${ref['color-white']}}`,
        'button-primary-inverted-hover-color': `${ref['color-brand-70']}`,

        'button-primary-focus-bg': `${ref['color-brand-50']}`,
        'button-primary-inverted-focus-bg': `${ref['color-white']}`,
        'button-primary-focus-border': `${ref['color-brand-50']}`,
        'button-primary-inverted-focus-border': `${ref['color-white']}`,
        'button-primary-focus-color': `${ref['color-white']}`,
        'button-primary-inverted-focus-color': `${ref['color-brand-50']}`,

        'button-primary-disabled-bg': `${ref['color-brand-20']}`,
        'button-primary-inverted-disabled-bg': `${ref['color-white']}`,
        'button-primary-disabled-border': `${ref['color-brand-20']}`,
        'button-primary-inverted-disabled-border': `${ref['color-white']}`,
        'button-primary-disabled-color': `${ref['color-white']}`,
        'button-primary-inverted-disabled-color': `${ref['color-brand-20']}`,

        'button-secondary-bg': `${ref['color-white']}`,
        'button-secondary-inverted-bg': 'transparent',
        'button-secondary-border': `${ref['color-brand-50']}`,
        'button-secondary-inverted-border': `${ref['color-white']}`,
        'button-secondary-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-color': `${ref['color-white']}`,

        'button-secondary-hover-bg': `${ref['color-white']}`,
        'button-secondary-inverted-hover-bg': 'transparent',
        'button-secondary-hover-border': `${ref['color-brand-70']}`,
        'button-secondary-inverted-hover-border': `${ref['color-brand-20']}`,
        'button-secondary-hover-color': `${ref['color-brand-70']}`,
        'button-secondary-inverted-hover-color': `${ref['color-brand-20']}`,

        'button-secondary-focus-bg': `${ref['color-white']}`,
        'button-secondary-inverted-focus-bg': `${ref['color-brand-80']}`,
        'button-secondary-focus-border': `${ref['color-brand-50']}`,
        'button-secondary-inverted-focus-border': `${ref['color-brand-50']}`,
        'button-secondary-focus-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-focus-color': `${ref['color-white']}`,

        'button-secondary-disabled-bg': `${ref['color-white']}`,
        'button-secondary-inverted-disabled-bg': 'transparent',
        'button-secondary-disabled-border': `${ref['color-brand-20']}`,
        'button-secondary-inverted-disabled-border': `${ref['color-brand-50']}`,
        'button-secondary-disabled-color': `${ref['color-brand-20']}`,
        'button-secondary-inverted-disabled-color': `${ref['color-brand-50']}`,

        'button-tertiary-bg': 'transparent',
        'button-tertiary-inverted-bg': 'transparent',
        'button-tertiary-border': 'transparent',
        'button-tertiary-inverted-border': 'transparent',
        'button-tertiary-color': `${ref['color-neutral-65']}`,
        'button-tertiary-inverted-color': `${ref['color-white']}`,

        'button-tertiary-hover-bg': `${ref['color-neutral-15']}`,
        'button-tertiary-inverted-hover-bg': `${ref['color-brand-70']}`,
        'button-tertiary-hover-border': 'transparent',
        'button-tertiary-inverted-hover-border': 'transparent',
        'button-tertiary-hover-color': `${ref['color-black']}`,
        'button-tertiary-inverted-hover-color': `${ref['color-white']}`,

        'button-tertiary-focus-bg': `${ref['color-white']}`,
        'button-tertiary-inverted-focus-bg': `${ref['color-brand-80']}`,
        'button-tertiary-focus-border': `${ref['color-brand-50']}`,
        'button-tertiary-inverted-focus-border': `${ref['color-brand-50']}`,
        'button-tertiary-focus-color': `${ref['color-neutral-65']}`,
        'button-tertiary-inverted-focus-color': `${ref['color-white']}`,

        'button-tertiary-disabled-bg': 'transparent',
        'button-tertiary-inverted-disabled-bg': 'transparent',
        'button-tertiary-disabled-border': 'transparent',
        'button-tertiary-inverted-disabled-border': 'transparent',
        'button-tertiary-disabled-color': `${ref['color-neutral-30']}`,
        'button-tertiary-inverted-disabled-color': `${ref['color-brand-50']}`,

        'button-destructive-bg': `${ref['color-alert-50']}`,
        'button-destructive-inverted-bg': `${ref['color-white']}`,
        'button-destructive-border': `${ref['color-alert-50']}`,
        'button-destructive-inverted-border': `${ref['color-white']}`,
        'button-destructive-color': `${ref['color-white']}`,
        'button-destructive-inverted-color': `${ref['color-alert-50']}`,

        'button-destructive-hover-bg': `${ref['color-alert-70']}`,
        'button-destructive-inverted-hover-bg': `${ref['color-white']}`,
        'button-destructive-hover-border': `${ref['color-alert-70']}`,
        'button-destructive-inverted-hover-border': `${ref['color-white']}`,
        'button-destructive-hover-color': `${ref['color-white']}`,
        'button-destructive-inverted-hover-color': `${ref['color-alert-70']}`,

        'button-destructive-focus-bg': `${ref['color-alert-50']}`,
        'button-destructive-inverted-focus-bg': `${ref['color-white']}`,
        'button-destructive-focus-border': `${ref['color-alert-20']}`,
        'button-destructive-inverted-focus-border': `${ref['color-white']}`,
        'button-destructive-focus-color': `${ref['color-white']}`,
        'button-destructive-inverted-focus-color': `${ref['color-alert-20']}`,

        'button-destructive-disabled-bg': `${ref['color-alert-20']}`,
        'button-destructive-inverted-disabled-bg': `${ref['color-white']}`,
        'button-destructive-disabled-border': `${ref['color-alert-20']}`,
        'button-destructive-inverted-disabled-border': `${ref['color-white']}`,
        'button-destructive-disabled-color': `${ref['color-white']}`,
        'button-destructive-inverted-disabled-color': `${ref['color-alert-20']}`,

        'button-search-bg': `${ref['color-white']}`,
        'button-search-border': `${ref['color-neutral-65']}`,
        'button-search-color': `${ref['color-neutral-65']}`,
        'button-search-hover-bg': `${ref['color-neutral-15']}`,
        'button-search-hover-color': `${ref['color-black']}`,
        'button-search-disabled-bg': `${ref['color-neutral-05']}`,
        'button-search-disabled-border': `${ref['color-neutral-15']}`,
        'button-search-disabled-color': `${ref['color-neutral-30']}`,
    };
    return tokens;
};
