import { Theme, ComponentTokens } from './interface';

export const generateTokens = <T extends keyof ComponentTokens>(ref: Theme['ref']): Record<T, string> => {
    const tokens = {
        'focus-box-shadow': `0 0 0 2px ${ref['color-brand-20']}`,
        'focus-box-shadow-inset': `inset 0 0 0 2px ${ref['color-brand-20']}`,
        'focus-border-box-shadow': ` 0 0 0 1px ${ref['color-brand-50']}, 0 0 0 3px ${ref['color-brand-20']}`,
        'focus-border-box-shadow-inset': `inset 0 0 0 2px ${ref['color-brand-20']}, inset 0 0 0 3px ${ref['color-brand-50']}`,
        'focus-border': `${ref['color-brand-50']}`,
        'modal-overlay-background-color': 'rgba(0, 0, 0, 0.75)',
        'overlay-box-shadow': '0 10px 20px 0 rgba(0, 0, 0, 0.19)',

        'button-primary-background-color': `${ref['color-brand-50']}`,
        'button-primary-inverted-background-color': `${ref['color-white']}`,
        'button-primary-border-color': `${ref['color-brand-50']}`,
        'button-primary-inverted-border-color': `${ref['color-white']}`,
        'button-primary-text-color': `${ref['color-white']}`,
        'button-primary-inverted-text-color': `${ref['color-brand-50']}`,

        'button-primary-hover-background-color': `${ref['color-brand-70']}`,
        'button-primary-inverted-hover-background-color': `${ref['color-white']}`,
        'button-primary-hover-border-color': `${ref['color-brand-70']}`,
        'button-primary-inverted-hover-border-color': `${ref['color-white']}`,
        'button-primary-hover-text-color': `${ref['color-white']}}`,
        'button-primary-inverted-hover-text-color': `${ref['color-brand-70']}`,

        'button-primary-focus-background-color': `${ref['color-brand-50']}`,
        'button-primary-inverted-focus-background-color': `${ref['color-white']}`,
        'button-primary-focus-border-color': `${ref['color-brand-50']}`,
        'button-primary-inverted-focus-border-color': `${ref['color-white']}`,
        'button-primary-focus-text-color': `${ref['color-white']}`,
        'button-primary-inverted-focus-text-color': `${ref['color-brand-50']}`,

        'button-primary-disabled-background-color': `${ref['color-brand-20']}`,
        'button-primary-inverted-disabled-background-color': `${ref['color-white']}`,
        'button-primary-disabled-border-color': `${ref['color-brand-20']}`,
        'button-primary-inverted-disabled-border-color': `${ref['color-white']}`,
        'button-primary-disabled-text-color': `${ref['color-white']}`,
        'button-primary-inverted-disabled-text-color': `${ref['color-brand-20']}`,

        'button-secondary-background-color': `${ref['color-white']}`,
        'button-secondary-inverted-background-color': 'transparent',
        'button-secondary-border-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-border-color': `${ref['color-white']}`,
        'button-secondary-text-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-text-color': `${ref['color-white']}`,

        'button-secondary-hover-background-color': `${ref['color-white']}`,
        'button-secondary-inverted-hover-background-color': 'transparent',
        'button-secondary-hover-border-color': `${ref['color-brand-70']}`,
        'button-secondary-inverted-hover-border-color': `${ref['color-brand-20']}`,
        'button-secondary-hover-text-color': `${ref['color-brand-70']}`,
        'button-secondary-inverted-hover-text-color': `${ref['color-brand-20']}`,

        'button-secondary-focus-background-color': `${ref['color-white']}`,
        'button-secondary-inverted-focus-background-color': `${ref['color-brand-80']}`,
        'button-secondary-focus-border-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-focus-border-color': `${ref['color-brand-50']}`,
        'button-secondary-focus-text-color': `${ref['color-brand-50']}`,
        'button-secondary-inverted-focus-text-color': `${ref['color-white']}`,

        'button-secondary-disabled-background-color': `${ref['color-white']}`,
        'button-secondary-inverted-disabled-background-color': 'transparent',
        'button-secondary-disabled-border-color': `${ref['color-brand-20']}`,
        'button-secondary-inverted-disabled-border-color': `${ref['color-brand-50']}`,
        'button-secondary-disabled-text-color': `${ref['color-brand-20']}`,
        'button-secondary-inverted-disabled-text-color': `${ref['color-brand-50']}`,

        'button-tertiary-background-color': 'transparent',
        'button-tertiary-inverted-background-color': 'transparent',
        'button-tertiary-border-color': 'transparent',
        'button-tertiary-inverted-border-color': 'transparent',
        'button-tertiary-text-color': `${ref['color-neutral-65']}`,
        'button-tertiary-inverted-text-color': `${ref['color-white']}`,

        'button-tertiary-hover-background-color': `${ref['color-neutral-15']}`,
        'button-tertiary-inverted-hover-background-color': `${ref['color-brand-70']}`,
        'button-tertiary-hover-border-color': 'transparent',
        'button-tertiary-inverted-hover-border-color': 'transparent',
        'button-tertiary-hover-text-color': `${ref['color-black']}`,
        'button-tertiary-inverted-hover-text-color': `${ref['color-white']}`,

        'button-tertiary-focus-background-color': `${ref['color-white']}`,
        'button-tertiary-inverted-focus-background-color': `${ref['color-brand-80']}`,
        'button-tertiary-focus-border-color': `${ref['color-brand-50']}`,
        'button-tertiary-inverted-focus-border-color': `${ref['color-brand-50']}`,
        'button-tertiary-focus-text-color': `${ref['color-neutral-65']}`,
        'button-tertiary-inverted-focus-text-color': `${ref['color-white']}`,

        'button-tertiary-disabled-background-color': 'transparent',
        'button-tertiary-inverted-disabled-background-color': 'transparent',
        'button-tertiary-disabled-border-color': 'transparent',
        'button-tertiary-inverted-disabled-border-color': 'transparent',
        'button-tertiary-disabled-text-color': `${ref['color-neutral-30']}`,
        'button-tertiary-inverted-disabled-text-color': `${ref['color-brand-50']}`,

        'button-destructive-background-color': `${ref['color-alert-50']}`,
        'button-destructive-inverted-background-color': `${ref['color-white']}`,
        'button-destructive-border-color': `${ref['color-alert-50']}`,
        'button-destructive-inverted-border-color': `${ref['color-white']}`,
        'button-destructive-text-color': `${ref['color-white']}`,
        'button-destructive-inverted-text-color': `${ref['color-alert-50']}`,

        'button-destructive-hover-background-color': `${ref['color-alert-70']}`,
        'button-destructive-inverted-hover-background-color': `${ref['color-white']}`,
        'button-destructive-hover-border-color': `${ref['color-alert-70']}`,
        'button-destructive-inverted-hover-border-color': `${ref['color-white']}`,
        'button-destructive-hover-text-color': `${ref['color-white']}`,
        'button-destructive-inverted-hover-text-color': `${ref['color-alert-70']}`,

        'button-destructive-focus-background-color': `${ref['color-alert-50']}`,
        'button-destructive-inverted-focus-background-color': `${ref['color-white']}`,
        'button-destructive-focus-border-color': `${ref['color-alert-20']}`,
        'button-destructive-inverted-focus-border-color': `${ref['color-white']}`,
        'button-destructive-focus-text-color': `${ref['color-white']}`,
        'button-destructive-inverted-focus-text-color': `${ref['color-alert-20']}`,

        'button-destructive-disabled-background-color': `${ref['color-alert-20']}`,
        'button-destructive-inverted-disabled-background-color': `${ref['color-white']}`,
        'button-destructive-disabled-border-color': `${ref['color-alert-20']}`,
        'button-destructive-inverted-disabled-border-color': `${ref['color-white']}`,
        'button-destructive-disabled-text-color': `${ref['color-white']}`,
        'button-destructive-inverted-disabled-text-color': `${ref['color-alert-20']}`,

        'button-search-background-color': `${ref['color-white']}`,
        'button-search-border-color': `${ref['color-neutral-65']}`,
        'button-search-text-color': `${ref['color-neutral-65']}`,
        'button-search-hover-background-color': `${ref['color-neutral-15']}`,
        'button-search-hover-text-color': `${ref['color-black']}`,
        'button-search-disabled-background-color': `${ref['color-neutral-05']}`,
        'button-search-disabled-border-color': `${ref['color-neutral-15']}`,
        'button-search-disabled-text-color': `${ref['color-neutral-30']}`,
    } as Record<T, string>;

    return tokens;
};
