import { Theme } from './theme';

export const generateTokens = (theme: Omit<Theme, 'tokens'>): Theme['tokens'] => {
    const { main, greys, notifications } = theme;

    const tokens: Theme['tokens'] = {
        'focus-box-shadow': `0 0 0 2px ${main['primary-1.2']}`,
        'focus-border-box-shadow': ` 0 0 0 1px ${main['primary-1.1']}, 0 0 0 3px ${main['primary-1.2']}`,
        'focus-border-box-shadow-inset': `inset 0 0 0 2px ${main['primary-1.2']}, inset 0 0 0 3px ${main['primary-1.1']}`,
        'focus-border': `${main['primary-1.1']}`,
        'modal-overlay-background-color': 'rgba(0, 0, 0, 0.75)',
        'overlay-box-shadow': '0 10px 20px 0 rgba(0, 0, 0, 0.19)',
        'button-primary': {
            bg: `${main['brand-50']}`,
            'inverted-bg': `${greys.white}`,
            border: `${main['brand-50']}`,
            'inverted-border': `${greys.white}`,
            color: `${greys.white}`,
            'inverted-color': `${main['brand-50']}`,

            'hover-bg': `${main['brand-70']}`,
            'inverted-hover-bg': `${greys.white}`,
            'hover-border': `${main['brand-70']}`,
            'inverted-hover-border': `${greys.white}`,
            'hover-color': `${greys.white}}`,
            'inverted-hover-color': `${main['brand-70']}`,

            'focus-bg': `${main['brand-50']}`,
            'inverted-focus-bg': `${greys.white}`,
            'focus-border': `${main['brand-50']}`,
            'inverted-focus-border': `${greys.white}`,
            'focus-color': `${greys.white}`,
            'inverted-focus-color': `${main['brand-50']}`,

            'disabled-bg': `${main['brand-20']}`,
            'inverted-disabled-bg': `${greys.white}`,
            'disabled-border': `${main['brand-20']}`,
            'inverted-disabled-border': `${greys.white}`,
            'disabled-color': `${greys.white}`,
            'inverted-disabled-color': `${main['brand-20']}`,
        },
        'button-secondary': {
            bg: `${greys.white}`,
            'inverted-bg': 'transparent',
            border: `${main['brand-50']}`,
            'inverted-border': `${greys.white}`,
            color: `${main['brand-50']}`,
            'inverted-color': `${greys.white}`,

            'hover-bg': `${greys.white}`,
            'inverted-hover-bg': 'transparent',
            'hover-border': `${main['brand-70']}`,
            'inverted-hover-border': `${main['brand-20']}`,
            'hover-color': `${main['brand-70']}`,
            'inverted-hover-color': `${main['brand-20']}`,

            'focus-bg': `${greys.white}`,
            'inverted-focus-bg': `${main['brand-80']}`,
            'focus-border': `${main['brand-50']}`,
            'inverted-focus-border': `${main['brand-50']}`,
            'focus-color': `${main['brand-50']}`,
            'inverted-focus-color': `${greys.white}`,

            'disabled-bg': `${greys.white}`,
            'inverted-disabled-bg': 'transparent',
            'disabled-border': `${main['brand-20']}`,
            'inverted-disabled-border': `${main['brand-50']}`,
            'disabled-color': `${main['brand-20']}`,
            'inverted-disabled-color': `${main['brand-50']}`,
        },
        'button-tertiary': {
            bg: 'transparent',
            'inverted-bg': 'transparent',
            border: 'transparent',
            'inverted-border': 'transparent',
            color: `${greys['neutral-65']}`,
            'inverted-color': `${greys.white}`,

            'hover-bg': `${greys['neutral-15']}`,
            'inverted-hover-bg': `${main['brand-70']}`,
            'hover-border': 'transparent',
            'inverted-hover-border': 'transparent',
            'hover-color': `${greys.black}`,
            'inverted-hover-color': `${greys.white}`,

            'focus-bg': `${greys.white}`,
            'inverted-focus-bg': `${main['brand-80']}`,
            'focus-border': `${main['brand-50']}`,
            'inverted-focus-border': `${main['brand-50']}`,
            'focus-color': `${greys['neutral-65']}`,
            'inverted-focus-color': `${greys.white}`,

            'disabled-bg': 'transparent',
            'inverted-disabled-bg': 'transparent',
            'disabled-border': 'transparent',
            'inverted-disabled-border': 'transparent',
            'disabled-color': `${greys['neutral-30']}`,
            'inverted-disabled-color': `${main['brand-50']}`,
        },
        'button-destructive': {
            bg: `${notifications['alert-50']}`,
            'inverted-bg': `${greys.white}`,
            border: `${notifications['alert-50']}`,
            'inverted-border': `${greys.white}`,
            color: `${greys.white}`,
            'inverted-color': `${notifications['alert-50']}`,

            'hover-bg': `${notifications['alert-70']}`,
            'inverted-hover-bg': `${greys.white}`,
            'hover-border': `${notifications['alert-70']}`,
            'inverted-hover-border': `${greys.white}`,
            'hover-color': `${greys.white}`,
            'inverted-hover-color': `${notifications['alert-70']}`,

            'focus-bg': `${notifications['alert-50']}`,
            'inverted-focus-bg': `${greys.white}`,
            'focus-border': `${notifications['alert-20']}`,
            'inverted-focus-border': `${greys.white}`,
            'focus-color': `${greys.white}`,
            'inverted-focus-color': `${notifications['alert-20']}`,

            'disabled-bg': `${notifications['alert-20']}`,
            'inverted-disabled-bg': `${greys.white}`,
            'disabled-border': `${notifications['alert-20']}`,
            'inverted-disabled-border': `${greys.white}`,
            'disabled-color': `${greys.white}`,
            'inverted-disabled-color': `${notifications['alert-20']}`,
        },
        'button-search': {
            bg: `${greys.white}`,
            border: `${greys['neutral-65']}`,
            color: `${greys['neutral-65']}`,
            'hover-bg': `${greys['neutral-15']}`,
            'hover-color': `${greys.black}`,
            'disabled-bg': `${greys['neutral-05']}`,
            'disabled-border': `${greys['neutral-15']}`,
            'disabled-color': `${greys['neutral-30']}`,
        },
    };
    return tokens;
};
