name: Triage

on:
  pull_request_target:
    types:
      - opened
      - reopened

jobs:
  assign-project:
    name: Assign to Overwatch project
    runs-on: ubuntu-latest
    steps:
      - uses: alex-page/github-project-automation-plus@v0.7.1
        with:
          project: Overwatch
          column: To review
          repo-token: ${{ secrets.GH_PROJECT_TOKEN }}
